### ISSUE TITLE
Nonliteral value in nominal attribute in radiator example

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#128]
The following check gives a non-literal value:
```
Check of Annex60.Fluid.HeatExchangers.Radiators.Examples.RadiatorEN442_2:

 Non-literal value.

In nominal attribute for res2.m_flow.
Ignoring nominal attribute.
```

**Comment by thorade** [comment]
With `Advanced.PedanticModelica=true` the command `checkModel("Annex60.Fluid.HeatExchangers.Radiators.Examples.RadiatorEN442_2");` no longer gives the nonliteral value error.
The `Attempting to redeclare ThermodynamicState` persists.

**Comment by thorade** [comment]
OK, the nonliteral value is just a warning, and it is only displayed when checking in non-pedantic mode.

**Comment by thorade** [comment]
Also see  https://github.com/open-ideas/IDEAS/issues/165
