### ISSUE TITLE
FixedResistanceDpM revision

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#129]
This model needs two revision:
First, it uses `Fluid/BaseClasses/PartialResistance.mo` assigns `m_flow(start=0)` which is already assigned in its base class. This can be removed. 

Second, `FixedResistances/FixedResistanceDpM.mo` uses
```
if ( m_flow_turbulent > m_flow_nominal_pos) then
   Modelica.Utilities.Streams.print("Warning: In FixedResistanceDpM ....
```
This should use `assert(..., ..., AssertionLevel.warning);`

**Comment by damienpicard** [comment]
Issue129 resistance has been merged.
