### ISSUE TITLE
Move Buildings.BoundaryConditions to Annex60

### ISSUE THREAD

**Issue by marcusfuchs** [iea-annex60/modelica-annex60#150]
This is needed for the Air Flow Benchmark

**Comment by mwetter** [comment]
@marcusfuchs : You should be able to merge the branch `issue150_boundaryConditions` into your branch for the numerical experiments.

I did not yet issue a pull request as the following items should be discussed with the team prior to merging it to the master (and the code needs to be reviewed as usual):

The following new packages had to be added, but this could be refactored if the team sees any problems with it:
- `Annex60.Utilities.Time` This contains a block that outputs the model time. This package could also be used to add models that indicate for example whether the current model time is a week-day, holiday etc., or whether daylight saving time is currently active.
- `Annex60.HeatTransfer.Types.Azimuth` and `Annex60.HeatTransfer.Types.Tilt`. I think these belong to the `HeatTransfer` package, which does not yet exist in `Annex60`. These types are also used in `BoundaryConditions` to compute the incident solar radiation.

**Comment by mwetter** [comment]
Leuven and Aachen agrees to move it to the master.
Need to check with @thorade whether Berlin agrees with this merge.

**Comment by thorade** [comment]
After discussion with @nytschgeusen we have no objections to an `Annex60.Utilities.Time` block.
The two enumerations `Azimuth` and `Tilt` also look useful, but we see the need for further discussion regarding the path: We already have some heat transfer stuff in our library and do not want to introduce another `HeatTransfer` package. Is storing these two enumerations elsewhere an option?  Would there be anything else in the `HeatTransfer` package?

**Comment by mwetter** [comment]
@thorade , @nytschgeusen : `Types.Azimuth` and `Types.Tilt` are used in the `Buildings` library in
```
Buildings.BoundaryConditions (to compute solar irradiation)
Buildings.Fluid.Sources.Outside_CpLowRise (to compute wind pressure)
Buildings.HeatTransfer
Buildings.Rooms
```
Therefore, following our (not yet written up?) convention that `Types` should be at the top-level of all packages that contain classes that require these types, the correct location should be `Annex60.Types.Azimuth` and `Annex60.Types.Tilt`.
What do others (@mlauster, @marcusfuchs, @Mathadon etc.) think about this location? 

Regarding other potential heat transfer models, currently in `Buildings.HeatTransfer`, we have the packages `Conduction`, `Convection`, `Sources`, `Radiosity`, `Windows`, `Data`, `Types` and `Interfaces`. E.g., these are the heat transfer components that we use to build a room.

**Comment by Mathadon** [comment]
I do not have a strong opinion on where ```Types``` should be stored but your suggestion sounds logical so that's great for me!

**Comment by marcusfuchs** [comment]
Same here: No strong opinion and openess to the given logic.

**Comment by thorade** [comment]
So it sums upt to introducing three new classes, in the following locations:
- `Annex60.Utilities.Time`
- `Annex60.Types.Azimuth`
- `Annex60.Types.Tilt`
That is fine for me, and I think also for @nytschgeusen
