### ISSUE TITLE
Derivatives of smoothMax, smoothMin, smoothLimit

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#152]
I have made an implementation of the derivatives of function smoothMin, smoothMax and smoothLimit. There is however some numerical issue that I would like to discuss. I will first make a new branch.

**Comment by Mathadon** [comment]
The commit can be found on https://github.com/Mathadon/modelica-annex60/tree/issue152_derMaxMinLimit 

I have added two models to validate the derivative implementation:
```Annex60.Utilities.Math.Examples.SmoothMax```
and
```Annex60.Utilities.Math.Examples.SmoothLimit```

I first calculate the derivative of the output of the ```SmoothMax``` or ```Limit``` blocks using ```der()```. I then integrate this result again. This should result in the original signal. This test works correctly for the ```SmoothMax``` example:
![screen shot 2015-01-16 at 10 33 35](https://cloud.githubusercontent.com/assets/5970879/5774149/260dd2b0-9d6b-11e4-9791-9e8e9ecc2340.png)

But not for the ```SmoothLimit``` example:

![screen shot 2015-01-16 at 10 34 00](https://cloud.githubusercontent.com/assets/5970879/5774158/404df4e8-9d6b-11e4-86b7-130e765c8d78.png)

When changing the solver from Dassl to Euler the result is a lot better:
![screen shot 2015-01-16 at 10 35 05](https://cloud.githubusercontent.com/assets/5970879/5774172/5c180768-9d6b-11e4-9a69-5feb77445be5.png)

This seems to suggest that there is something wrong with the Dassl solver. Does anybody have an idea what this could be caused by and/or if this is a bug?

**Comment by mwetter** [comment]
If it works with a different solver, then I think it is an error in Dymola, but I am surprised that such simple a model does not work. Did you contact Dassault?

I am also wondering why you need to provide derivatives. A tool should be able to automatically differentiate these functions. If Dymola does not differentiate these functions, did you try to add the `smoothOrder` annotation? In the `Buildings` library, we  don't provide implementations for the derivatives of these functions, but none of the examples require numerical differentiation.

**Comment by Mathadon** [comment]
I thought that Dymola cannot differentiate algorithm sections, and since functions contain algorithms that you had to provide these derivatives.

If I remove ```derivative=Annex60.Utilities.Math.Functions.BaseClasses.der_smoothLimit,``` then I get an error when running the example:
```
Cannot find differentiation function:
Annex60.Utilities.Math.Functions.smoothLimit(sine.y, 0, 0.5, 0.001)
with respect to time

Failed to differentiate the equation
smoLim.y = Annex60.Utilities.Math.Functions.smoothLimit(sine.y, 0, 0.5, 0.001);

in order to reduce the DAE index.

Failed to reduce the DAE index.
```
so I figured I need to add the derivative

However adding ```smoothOrder=1``` does indeed work, without derivative. I'll revert the change and add ```smoothOrder=1``` in the functions instead?

The solver still gives a wrong result though. I still have to contact Dassault.

**Comment by mwetter** [comment]
@Mathadon : Yes, I suggest you revert `der_smoothLimit` and add `smoothOrder=1` to these functions. Please also include it to `smoothMin` and `smoothMax` if they don't have it already.

**Comment by Mathadon** [comment]
The 'Dassl bug' goes away if you increase the tolerance to e-12. I also added ```smoothOrder``` for ```smoothHeaviside``` and ```inverseXRegularized```.

**Comment by Mathadon** [comment]
This has been merged
