### ISSUE TITLE
SteadyState massDynamics in ConservationEquation

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#170]
```ConservationEquation``` contains:

```
  if massDynamics == Modelica.Fluid.Types.Dynamics.SteadyState then
    0 = mb_flow + mWat_flow;
  else
    der(m) = mb_flow + mWat_flow;
  end if;
```
This is however not sufficient to guarantee that ```der(m) = 0``` since ```m = rho * V``` and often ```rho = f(p)```. The result is that variations in pressure can lead to variations in ```m```. An illustration:

![screen shot 2015-02-16 at 12 24 33](https://cloud.githubusercontent.com/assets/5970879/6211098/cb8fefce-b5d6-11e4-94a6-20c131b5b7a5.png)

![screen shot 2015-02-16 at 12 24 08](https://cloud.githubusercontent.com/assets/5970879/6211100/d09e3750-b5d6-11e4-875f-145253f36705.png)

As you can see the consequence is a temperature change because the specific internal energy drops when the pressure rises, since the mixing volume thinks ```m``` rises. Note that although energy is conserved, the second law of thermodynamics is violated.

I propose to change the ```ConservationEquation``` implementation such that 
```
  if massDynamics == Modelica.Fluid.Types.Dynamics.SteadyState then
    m = fluidVolume*rho_nominal;
  else
    m = fluidVolume*medium.d;
  end if;
```

Example code:
```
model test

  Annex60.Fluid.MixingVolumes.MixingVolume vol(
    m_flow_nominal=1,
    V=1,
    redeclare package Medium = Medium,
    energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial,
    massDynamics=Modelica.Fluid.Types.Dynamics.SteadyState,
    nPorts=1) annotation (Placement(transformation(extent={{-10,20},{10,40}})));
  Annex60.Fluid.Sources.Boundary_pT bou(          redeclare package Medium =
        Medium,
    use_p_in=true,
    nPorts=1)
    annotation (Placement(transformation(extent={{-60,10},{-40,30}})));
  Modelica.Blocks.Sources.Pulse pulse(
    amplitude=1e5,
    period=1,
    offset=1e5)
    annotation (Placement(transformation(extent={{-100,10},{-80,30}})));
  replaceable package Medium = Buildings.Media.GasesPTDecoupled.SimpleAir;
equation 
  connect(pulse.y, bou.p_in) annotation (Line(
      points={{-79,20},{-74,20},{-74,22},{-62,22},{-62,28}},
      color={0,0,127},
      smooth=Smooth.None));
  connect(bou.ports[1], vol.ports[1]) annotation (Line(
      points={{-40,20},{0,20}},
      color={0,127,255},
      smooth=Smooth.None));
  annotation (uses(Annex60(version="0.2"), Modelica(version="3.2.1"),
      Buildings(version="1.7")),                                     Diagram(
        coordinateSystem(preserveAspectRatio=false, extent={{-100,-100},{100,100}}),
        graphics),
    experiment(
      StopTime=10,
      __Dymola_NumberOfIntervals=5000,
      Tolerance=1e-07,
      __Dymola_Algorithm="Radau"),
    __Dymola_experimentSetupOutput);
end test;
```

I will make a pull request!

**Comment by Mathadon** [comment]
The code is on https://github.com/Mathadon/modelica-annex60/tree/issue170_massDynamics
different results were generated by ```Annex60.Fluid.MassExchangers.Examples.Humidifier_u``` but I find it difficult to assess their correctness. I hope you can have a  look at it and update the results?

**Comment by Mathadon** [comment]
@mwetter have you had a chance to look at this?

**Comment by mwetter** [comment]
The example model that you provide does indeed change the mass (prior to your change) while `vol.dynBal.mb_flow=0` (and `mb_flow = sum(ports.m_flow)`), hence mass is created. This is because `fluidVolume` is constant but `medium.d` changes with pressure. Hence, `m` changes. However, `mb_flow=0` and therefore mass is created/destroyed as it cannot enter into the control volume through the fluid port.
I therefore think we should accept your proposed change. This effectively means that the mass remains constant even if the density changes, and therefore the volume expands/contracts.

@marcusfuchs and @mlauster: do you agree with this change?

The plot below has been created prior to your change, with `Modelica.Media.Air.SimpleAir`.
![mass](https://cloud.githubusercontent.com/assets/1329080/6521344/94030eca-c38b-11e4-9c9d-83960fcf0603.png)

**Comment by marcusfuchs** [comment]
I agree with this change. This is an interesting effect, thanks @Mathadon for pointing that out.

**Comment by mlauster** [comment]
I'm also fine with it. The new results look like what user will expect when they choose steady state mass dynamics.

**Comment by mwetter** [comment]
This is now on the `master`.
@Mathadon : it would be good if you can implement a unit test that produces the correct results, but produced the wrong result prior to this change. This way, we can ensure that we never revert the change without noticing. 
Currently, none of the unit tests produced different results, also not in the `Buildings` library.

**Comment by Mathadon** [comment]
I’ll do my best to addres this.
