### ISSUE TITLE
Remove inline=false for Media functions

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#191]
I see no reason why they should not be inlined. For example, `Modelica.Media.SimpleAir.specificEnthalpy` has also no inline annotation.

**Comment by thorade** [comment]
Maybe it was once `Inline=false, LateInline=true` as in some other Media functions and someone deleted the `LateInline` only?

**Comment by mwetter** [comment]
@thorade : do you see any demonstratable benefit in using `Inline=false, LateInline=true` rather than no annotation at all?

**Comment by thorade** [comment]
There can be a speed benefit when using BaseProperties that call a function that defines an annotation derivative (e.g. `Modelica.Media.Water.WaterIF97_base.BaseProperties` call `density_ph`, which then calls some function that calls `setState_ph`; during symbolic manipulation you want the function that defines the annotation derivative, but during simulation you want the inlined function that calls the setState_ph. Another example would be `Modelica.Media.Air.ReferenceMoistAir.Utilities.rho_pTx`).

That is not the case with `Annex60.Media.Air`, so removing the annotation as in your commit seems to be just fine.
