### ISSUE TITLE
Types Azimuth and Tilt 

### ISSUE THREAD

**Issue by thorade** [iea-annex60/modelica-annex60#199]
Something went wrong and we now have 
[Annex60.HeatTransfer.Types.Azimuth](https://github.com/iea-annex60/modelica-annex60/tree/master/Annex60/HeatTransfer/Types)
as well as 
[Annex60.Types.Azimuth](https://github.com/iea-annex60/modelica-annex60/tree/master/Annex60/Types).

The first one should be removed.

**Comment by thorade** [comment]
Until now, the second one is also not used -  is that true?

**Comment by mwetter** [comment]
I will add `Types.Azimuth` to
`Annex60.BoundaryConditions.SolarGeometry.Examples.IncidenceAngle`
