### ISSUE TITLE
Revise Utilities.Functions

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#2]
Revise the package `Utilities.Functions` so that for each function, there is a corresponding block and vice versa.

**Comment by mwetter** [comment]
@marcusfuchs : Examples for the function `smoothHeaviside` and the block `SmoothHeaviside` still need to be added:
``` 
mbp:Annex60 mwetter$ find . -name '*moothHeaviside*'
./Utilities/Math/Functions/smoothHeaviside.mo
./Utilities/Math/SmoothHeaviside.mo
```

**Comment by marcusfuchs** [comment]
Created one example for SmoothHeaviside and linked to that example in the documentation of the function and the block.
