### ISSUE TITLE
Steady state "steBal" implementation of MixingVolume

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#224]
This issue is for handling a discussion we had with @damienpicard , etc, during the Galway meeting.

In ```PartialMixingVolume``` a parameter is defined:

```
final parameter Boolean useSteadyStateTwoPort=(nPorts == 2) and 
      prescribedHeatFlowRate and (
      energyDynamics == Modelica.Fluid.Types.Dynamics.SteadyState) and (
      massDynamics == Modelica.Fluid.Types.Dynamics.SteadyState) and (
      substanceDynamics == Modelica.Fluid.Types.Dynamics.SteadyState) and (
      traceDynamics == Modelica.Fluid.Types.Dynamics.SteadyState)
```

When this is true then a different implementation of the mixing volume is used, although it is not clear to me why this is being done since the dynamic balance implementation is able to handle steady state equations as well.
What is the reason for this difference? Possibly the special implementation can be removed.

**Comment by Mathadon** [comment]
Apparently ```steBal``` allows for a more efficient implementation since ```actualStream``` need not be used. This should be checked and documented. Also ```steBal``` could be integrated into ```dynBal``` to avoid code duplication.

**Comment by mwetter** [comment]
Michael will add and revise documentation.

**Comment by mwetter** [comment]
@Mathadon : This has been addressed in https://github.com/iea-annex60/modelica-annex60/pull/238
Please close this ticket if that addresses your concerns.
