### ISSUE TITLE
Fluid.Movers.FlowControlled_dp has wrong sign for dp_actual

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#226]
This component has connectors `dp_in` and `dp_actual`. It multiplies `dp_in` by a gain of `-1` before sending it to the filter and from there to `dp_actual`, or it sends it directly to `dp_actual`.

The gain should be moved to the input of `preSou` so that `dp_in` and `dp_actual` have the same sign. This also avoids a warning because both of these variables declare `min=0`. It also makes the model more consistent with the other movers which all have `*_in = *_actual` if the filter is removed.

**Comment by Mathadon** [comment]
I think I addressed this in the pull request for the stage inputs for movers.

**Comment by mwetter** [comment]
@Mathadon I will fix it before addressing the other pull request and then resolve any potential conflicts as I need this model for Buildings 2.0.0 which is already a release candidate and hence I don't want to make too drastic changes at this point.
