### ISSUE TITLE
Wet vs dry air mass flow rate as fluid port variable

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#234]
Based on the following equation in ```ConservationEquation```:
```
0 = mb_flow + mWat_flow;
```
variables ```m_flow``` in fluid ports describe the mass flow rate of the wet air. A different option would be to use the mass flow rate of dry air. This would make it easier to keep thermal, pressure and moisture calculations decoupled since the mass flow rate would no longer depend on the moisture level. This would require that the pressure drop in ```FixedResistanceDpM``` is calculated based on the dry air mass flow rate, ie. the implementation of ```FixedResistanceDpM``` should remain as it is now. I am actually not sure if this would be physically more or less accurate than the current implementation. 

Is there a specific reason for the current implementation?

**Comment by mwetter** [comment]
Needs further analysis and prototype implementation.

It would also be good to know what mass flow rate is used in NMF, whether it is dry air or total mass of air.

**Comment by mwetter** [comment]
This is a dublicate of #247 and hence will be closed.
