### ISSUE TITLE
Types Azimuth and Tilt

### ISSUE THREAD

**Issue by thorade** [iea-annex60/modelica-annex60#252]
The comments for the two types Azimuth and Tilt say they are Enumerations, but they are not (they are packages with a list of constants). Should that be changed? Does one or the other solution have advantages? 

Also see section 4.8.5 of the Modelica 3.3 Specification:
https://www.modelica.org/documents/ModelicaSpec33.pdf#page=50

**Comment by mwetter** [comment]
They should be constants as they provide values. Enumerations will be the wrong data type. Could you please update the docs?

**Comment by thorade** [comment]
One more idea: Would it make sense to have two top-level directories, one called Types and one called Constants? And then move Azimuth and Tilt to the Constants directory?
