### ISSUE TITLE
Fixed mSenFac in FourPortHeatMassExchanger.mo

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#258]
```FourPortHeatMassExchanger.mo``` currently contains:
```
final mSenFac=1
```

in the mixing volumes. I'd like to remove this since in some cases we'd like to use this parameter. For instance in the model of a heat pump if we want to artificially increase the time constant of the model.

I'll make a pull request.

**Comment by mwetter** [comment]
Please go ahead and make the pull request without the final keyword, but
leave the default assignment of mSenFac=1.
This should also use Evaluate=true to avoid the overhead that is incurred
if mSenFac > 1.
