### ISSUE TITLE
Division by zero in Annex60.Fluid.Interfaces.StaticTwoPortConservationEquation

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#280]
In some cases a division by zero occurs in ```Annex60.Fluid.Interfaces.StaticTwoPortConservationEquation```. Consider the following example:

![screen shot 2015-06-30 at 09 49 55](https://cloud.githubusercontent.com/assets/5970879/8426340/533e25d4-1f0f-11e5-9558-3d1cf180060d.png)

the mixing volume is steady state. Due to the prescribed temperature the outlet temperature is known. The heat flow rate ```vol.heatPort.Q_flow``` then is by default computed from the known outlet and inlet enthalpies:

```
port_b.h_outflow = inStream(port_a.h_outflow) + Q_flow * m_flowInv;
```

After analytical processing this leads to:

```
vol.heatPort.Q_flow := vol.ports[2].h_outflow/vol.steBal.m_flowInv;
```

Since m_flowInv=0 when m_flow=0 this leads to a division by zero:
```
Error: Singular inconsistent scalar system for vol.heatPort.Q_flow = (sou.ports[1].h_outflow-vol.ports[2].h_outflow)/( -vol.steBal.m_flowInv) = 5072.7/-0
```

This can be fixed by setting:
```
vol(steBal(use_safeDivision=false))
```

since then the equation becomes:
```
port_a.m_flow * (inStream(port_a.h_outflow) - port_b.h_outflow) = -Q_flow;
```

which can be solved directly for ```Q_flow```

I propose to add a parameter ```prescribedTemperature``` in ```PartialMixingVolume``` similar to ```prescribedHeatFlowRate``` and set ```use_safeDivision = not prescribedTemperature ```. Does this seem a good approach or should we think about a formulation that does not require additional parameters?

**Comment by Mathadon** [comment]
See https://github.com/Mathadon/modelica-annex60/tree/issue280_divZeroMixVol for example and future unit test

**Comment by mwetter** [comment]
@Mathadon : Shouldn't you use `HeaterCooler_T` if you want to have ideal control on the outlet temperature (optionally, with a limit on the maximum capacity which I believe you will need for reasonable applications)?

**Comment by Mathadon** [comment]
Yes, you could argue about that but the problem does not only arise when setting a fixed temperature boundary, as illustrated in https://github.com/iea-annex60/modelica-annex60/issues/282. I propose to continue the discussion in that issue.
