### ISSUE TITLE
Exposing U in conservationEquation

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#292]
I'm checking if energy is conserved in one of my models and also in IDEAS. Therefore I need to be able to add up all internal energy of the models. U in `conservationEquation` is part of this, but `dynBal` is a protected model. I'd like to expose U by either making `dynBal` public or by adding a new variable U in `partialMixingVolume`. This variable can be set to 0 when using steadyState equations.

How can I proceed best?

**Comment by mwetter** [comment]
You can run the model using `Advanced.StoreProtectedVariables:= true;` in Dymola. If you want to automate it, you can use 
```
from buildingspy.simulate.Simulator import Simulator
s=Simulator("myPackage.myModel", "dymola")
s.addPreProcessingStatement("Advanced.StoreProtectedVariables:= true;")
s.simulate()
```
See also http://simulationresearch.lbl.gov/modelica/buildingspy/simulate.html#module-buildingspy.simulate.Simulator

**Comment by Mathadon** [comment]
But then I still get warnings, no?

**Comment by Mathadon** [comment]
Oh and I'm trying to do this 'on line', not with post processing. So the problem is I get warnings when directly using `vol.dynBal.U`.

**Comment by mwetter** [comment]
I guess that is primarily for your development. When I had a similar need, I made my own branch, removed the `protected` statement, and used that branch for my tests. You can still merge other changes from your `master` (or any other branch). Git should notice that you removed the `protected` after you made a new branch and hence should not overwrite it in subsequent merges.

This is how I work for example on https://github.com/lbl-srg/modelica-buildings/tree/zeroFlow which has special constructs that I only need for benchmarking but I regularly merge all other developments into it.

**Comment by Mathadon** [comment]
I'm actually adding the option in IDEAS to check conservation of energy so that would not be very practical since every merge from Annex60 would require the `protected` modifier to be removed again.

**Comment by mwetter** [comment]
Why don't you just write models that conserve energy (except for tiny mass flow rates for numerical reasons)? I don't see why users rather than developers would want to have to check this frequently. This adds in my view output variables that are not needed. If we go that path, we may also need to provide outputs to check that mass is conserved, mass fractions are conserved, and trace substances are conserved. Also, in dynamic models you would need to keep track of inflowing enthalpy, outflowing enthalpy and stored internal energy to verify conservation of energy as the energy stored changes over time. I don't see what the use case is for that other than maybe a verification when developing models.

**Comment by Mathadon** [comment]
Energy may not be conserved due to bad connections etc, so creating good component models does not guarantee conservation of energy. Indeed, for large models a first verification should be to check if energy is conserved in the model, for which I'd have to keep track of all enthalpy/heat flowing into the system. I think this is a valid use case. 
We could output `m` instead of `p` and `U` instead of `T` as is currently done in `MixingVolume` since the former variables are already outputs from `ports` and `heatPort`. This would not increase the number of outputs.

**Comment by Mathadon** [comment]
To be clear: I prefer just adding U and to keep T.

**Comment by mwetter** [comment]
Can you provide an model with a "bad connection"? Based on the connection
semantics of Modelica, connections should preserve energy and mass.
Otherwise, there may be a flaw in the implementation or in the solver that
needs to be corrected.

**Comment by Mathadon** [comment]
For instance: 1) Setting ```allowFlowReversal = false``` and then reversing the flow leads to problems. 2) If you're not careful with connecting instances of ```boundary_pT``` that only exist for setting an absolute pressure on the system, then mass can be drawn from these boundaries, which injects energy in the system. Both of these problems have happened before by accident and they sometimes go unnoticed. Therefore a proper verification is desirable.

Since you do not really seem to be in favour of the proposal I will handle this by making a duplicate in IDEAS.
