### ISSUE TITLE
Graphical differentiation of A60 models

### ISSUE THREAD

**Issue by rubenbaetens** [iea-annex60/modelica-annex60#294]
After merging the `Annex60` models into `IDEAS`, we noticed it's hard to differentiate between the models made in the Annex and made by our selve. 

That is, e.g. the package icons are similar or have the same style, which of course gives a homogeneous impression in a library but which also makes it difficult to find the added value of a developed library based on the Annex components.

Maybe we should give the packages in the annex60 library a strong or typical icon which will always be recognized when used in other libraries ?

**Comment by thorade** [comment]
I think I like the idea of having similar icons everywhere. 
Could the `.copiedFiles.txt` file be used somehow in this context?

**Comment by mwetter** [comment]
I think the icons should be similar so that the appearance is more homogeneous, and also because typical users probably don't care much about where the models come from. We could identify in the release notes something like "x out of y models and functions are from the Annex 60 library."

**Comment by mwetter** [comment]
An option would be to add in release notes or acknowledgement
```
100 out of 500 models and functions are from the Annex 60 library, commit #xxxx
```
Adding a commit to each model would not be good as it causes changes during each commit.
An option would be to add in each model a string such as
```
This class has been merged from the Annex 60 library. (or has been developed within IEA EBC Annex 60).
```

**Comment by thorade** [comment]
The URL of each file on github also does not change and could be added. 
Would also be possible to link to the "blame" view, e.g. 
https://github.com/iea-annex60/modelica-annex60/blame/master/Annex60/package.mo

**Comment by rubenbaetens** [comment]
It's true that a typical user doesn't care much about who made which model, the question popped-up more from a developer or an internal user  point of view who wants to address a question to the original developer of the model ...

I like the idea of noting the 'x out of y models come from A60' which gives a first indication. You might differentiate here between baseclass-like models (in which the typical user might have no main interest in) and end-user models.

**Comment by thorade** [comment]
A related comment:
Currently the merge script will create the file `.copiedFiles.txt` and the first two lines look like:
```
# Do not edit this file unless you know what you are doing.
# This file is used by the Annex60 merge script and generated by BuildingsPy.
```
It would be nice it there could be a third line saying which commit (identified by its SHA) was used for the merge.

**Comment by rubenbaetens** [comment]
This issue could be closed actually.
