### ISSUE TITLE
No license description

### ISSUE THREAD

**Issue by choeger** [iea-annex60/modelica-annex60#308]
The repository lacks an (easily accessible) license file. Under what license is it released?

**Comment by mwetter** [comment]
See https://github.com/iea-annex60/modelica-annex60/blob/master/Annex60/legal.html

The file is in the Annex60 subdirectory because Modelica libraries do not include the top-level directory when they are installed.

**Comment by choeger** [comment]
Do you expect users to find that file without any further information? No automated tool and no casual user/optential contributor will find that file quickly. To me the library looked like many other propietary github projects, that way. There should be either a link to the file in the readme or (better) a markdown LICENSE.md file in the repository.

See http://pastebin.com/tQHssrEu for the Modelica License in md format.

**Comment by mwetter** [comment]
I added a link in README.md

Reproducing the file in md format will cause to have multiple versions which cannot be compared easily.
