### ISSUE TITLE
Supporting analytic ODE Jacobians

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#319]
Setting `Advanced.GenerateAnalyticJacobian=true` in dymola can lead to important speedups when using implicit solvers (I obtained a x10 speed increase for a small district model). Therefore it may be good to extend the unit tests to check if all models can be compiled using `Advanced.GenerateAnalyticJacobian=true` and to fix those models where this is not the case. This is very similar to the existing check for numeric Jacobians in algebraic loops.
We can then suggest to users to set `Advanced.GenerateAnalyticJacobian=true` in the user guide.

**Comment by mwetter** [comment]
I agree that having this capability would be good. We could add a flag to BuildingsPy that allows to specify a command such as `Advanced.GenerateAnalyticJacobian=true` before the tests are executed. The error message would be `Failed to generate analytic Jacobian for the ODE problem`

Do you have a sense of what models typically get faster? I made two tests, both lead to higher computing time with analytic Jacobians:
```
Buildings.Examples.Tutorial.Boiler.System7
Advanced.GenerateAnalyticJacobian=false: 7.7 seconds
Advanced.GenerateAnalyticJacobian=true: 12.7 seconds

Buildings.Examples.VAVReheat.ClosedLoop
Advanced.GenerateAnalyticJacobian=false: 51 seconds
Advanced.GenerateAnalyticJacobian=true: 125 seconds
```

**Comment by Mathadon** [comment]
That's somewhat unexpected but it seems to be in line with what the Dymola developers explained. I'm now a bit unsure about which Jacobian type will lead to faster models when. It may however be linked to the density of the Jacobian and/or its size. The district model speedup of a factor 10 seems to suggest that large, sparse Jacobians are accelerated. However the example in the paper seems to suggest that small, dense(?) Jacobians are evaluated faster analytically..

**Comment by thorade** [comment]
It is a pity Dymola does not have better documentation for the flags.
The FCSys library also lists some flags that might influence simulation performance:
https://github.com/kdavies4/FCSys/blob/master/load.mos
What is the value of the flag `Hidden.UseNewTearing`? Migth depend on the Dymola version.
Francesco showed the Jacobian sparsity as a percentage number, can you print this information using Dymola?

**Comment by casella** [comment]
I don't know how to do it using Dymola, or whether this is possible at all.
In OpenModelica, just simulate the model with the simulation flag ```-lv LOG_SOLVER```. You get something like this:
```
LOG_SOLVER        | info    | sparse structure of jacobian A [size: 20x20]
|                 | |       | | 23 nonzero elements
```
Computing the sparsity ratio is then trivial.

**Comment by thorade** [comment]
I contacted Dymola support (via our reseller) and as a first step towards better analysis of the model structure they suggested to set the flag `Advanced.FMI.GenerateModelDescriptionInterface2 = true`. A new file `modelDescription.xml` will be created that contains a section `ModelStructure`. That section contains a lot of information about the model structure, but I do not understand it...
