### ISSUE TITLE
Use MSL compliant annotations in weather data reader

### ISSUE THREAD

**Issue by marcusfuchs** [iea-annex60/modelica-annex60#321]
@tbeu reported this to AixLib in RWTH-EBC/AixLib#107:

The weather data reader uses the annotation `__Dymola_loadSelector`. I see no difference in functionality when using `loadSelector`. Therefore I propose to change that also in Annex60. Will do that in a few minutes.

**Comment by mwetter** [comment]
Closed at it is merged to the master
