### ISSUE TITLE
use logo also for organization

### ISSUE THREAD

**Issue by thorade** [iea-annex60/modelica-annex60#328]
This is really not important, but I just found the EBC logo here:
https://github.com/iea-annex60/modelica-annex60/blob/master/Annex60/Resources/Images/iea-ebc-logo.png

Might be nice to use this also for the [iea-annex60 organization](https://github.com/iea-annex60), 
nicer than the current green pixel thing.

https://github.com/iea-annex60/settings/profile

**Comment by mwetter** [comment]
Thanks, I updated the logo.
