### ISSUE TITLE
import SI = Modelica.SIunits;

### ISSUE THREAD

**Issue by thorade** [iea-annex60/modelica-annex60#338]
There are two ways to use physical types:
```Modelica
parameter Modelica.SIunits.Torque tau;
parameter Modelica.SIunits.Angle phi;
```
or 
```Modelica
import SI = Modelica.SIunits;
parameter SI.Torque tau;
parameter SI.Angle phi;
```
If we place the import statement at the top level `package.mo` then we could use the shorter notation everywhere else in the library. Would that be helpful?

Related:https://github.com/xogeny/ModelicaBook/issues/75

**Comment by mwetter** [comment]
I can go either way. Our style guide does not mention either way.

What is position of the developers from Aachen and Leuven? Shall we adapt the first (longer) version or use `import SI = Modelica.SIunits`?

**Comment by Mathadon** [comment]
I prefer not using the import. We do have the 'guideline' to use full paths when instantiating models so it seems consistent to apply that rule here too.

**Comment by thorade** [comment]
I think the idea should be to always use unambiguous paths, so never use e.g. `Types.xyz` but always use `Annex60.Types.xyz` or `Annex60.Fluid.Types.xyz`. Using import does not introduce any ambiguity, so it seems to be absolutely acceptable.
Still, I do not have a strong opinion on this, the discussion came up for our library and we wanted to be consistent with Annex60.

**Comment by marcusfuchs** [comment]
We neither have any objections either way. I think not using the import may save a little bit of work with changing the existing models, but there does not seem to be anything fundamentally wrong with using it.

**Comment by mwetter** [comment]
To summarize, LBL and Leuven prefer not to use the import statement.
UdK does not care.
Aachen seems to have slight preference for not using it.

I therefore close this ticket. If someone objects, please reopen it again so we can discuss at the next call.
