### ISSUE TITLE
License.mo and LICENSE.html

### ISSUE THREAD

**Issue by thorade** [iea-annex60/modelica-annex60#343]
We want to use the standard Modelica 2 license for the BuildingSystems library. We saved the top level UsersGuide as a directory with several files, one of them is LICENSE.mo. That file contains a copy of the text from https://www.modelica.org/licenses As licensor, we used Berlin University of the Arts.
The file License.mo was then exported as HTML to a file LICENSE.HTML which we would like to place at the top level of the repository, next to the README.md. 
The file legal.html was deleted / not copied from Annex60.

Now my questions:
Is that an acceptable way to go or do we have to keep the legal.html file?
Where and how should we mention Annex60? In the Acknowledgements.mo? Also in the License.mo?

**Comment by mwetter** [comment]
I believe your approach is fine. I added to the Acknowledgments class of the `Buildings` library the following:
```
<p>
The core of this library is the Annex 60 library,
a free open-source library with basic models that codify best practices for
the implementation of models for building and community energy and control systems.
The Annex 60 library is developed at
<a href=\"https://github.com/iea-annex60/modelica-annex60\">
https://github.com/iea-annex60/modelica-annex60</a>
within the Annex 60 project
(<a href=\"http://www.iea-annex60.org\">http://www.iea-annex60.org</a>)
of the International Energy Agency's
<a href=\"http://www.iea-ebc.org/\">Energy in Buildings and Communities</a> Programme.
</p>
```
It would be good if all libraries use the same, so please let me know any suggested changes.

Maybe we should have similar wording in the README.md file.

**Comment by thorade** [comment]
OK, thanks. I will add that text to our Acknowledgements.mo
There is one related pull request, then this issue can be closed.
