### ISSUE TITLE
Remove showDesignFlowDirection

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#349]
The flag `showDesignFlowDirection` is in my view not needed as it should be clear that the flow is from port a to port b. Also, this feature is not consistently used now by models with two ports, and it is not used in model with four ports.

I therefore propose to remove this graphical annotation. What are the positions of Aachen, Leuven and UdK?

**Comment by mlauster** [comment]
I don't think we are using this, I'm fine with your proposal

**Comment by Mathadon** [comment]
The design flow direction itself is not useful, but the symbol indicating `allowFlowReversal`, which is linked to it, does have some use. It however does not work when the parameter value of `allowFlowReversal` is propagated so I propose to remove both, also because it's one of the only parameters having a coupled visual illustration.

**Comment by carlesRT** [comment]
after a while working with Modelica one internalizes that the design direction is `port_a to port_b`, being the arrow not necessary anymore.

But if `allowFlowReversal=false` it is important to connect correctly the pipe model. The arrow might help to detect any wrong connection. A bit easier than look at the `Fluidport` color (blue/white). I would suggest remove the boolean `showDesignFlowDirection` and to link the current annotations to `allowFlowReversal`. 

```Modelica
visible=not allowFlowReversal
```
Furthermore it tells the modeler whether `allowFlowReversal`is set to true or not.

**Comment by mwetter** [comment]
@carlesRT Your suggestion of `visible=not allowFlowReversal` sounds good. I will implement this on branch `issue351_exposingPorts` as there is overlap with this ticket (on the documentation).
