### ISSUE TITLE
Consider removing port_a_exposesState and port_b_exposesState

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#351]
Consider removing in `PartialTwoPort` the parameters
`port_a_exposesState` and `port_b_exposesState`.
I don't think any library is using this feature.

**Comment by mwetter** [comment]
I suggest to remove these parameters as they cannot be dynamically changed on the diagram layer. For example, change in `Movers.BaseClasses.PartialFlowMachine` the `extends` statement to be
```  
extends Buildings.Fluid.Interfaces.PartialTwoPortInterface(show_T=false,
    port_a_exposesState=energyDynamics <> Modelica.Fluid.Types.Dynamics.SteadyState,
```
Looking at `Movers.Validation.PumpCurveConstruction` shows that the icon still shows the graphical annotation despite that the pumps are configured to be steady-state.

I therefore suggest to remove these parameters. What is the position of Aachen, UdK and Leuven?

**Comment by mlauster** [comment]
From Aachen side, we are using this, but I'm not sure yet if it works in our cases. We need to check this.

**Comment by mlauster** [comment]
Aachen should be fine with removing this.

**Comment by Mathadon** [comment]
Ok, we never use it!

**Comment by carlesRT** [comment]
I think we also do not use it.

**Comment by Mathadon** [comment]
This seems to be merged.
