### ISSUE TITLE
Annex60.Fluid.Interfaces.FourPortHeatMassExchanger is not used

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#353]
The model `Annex60.Fluid.Interfaces.FourPortHeatMassExchanger` is not used anywhere in the library, and hence it is also not part of any regression test.
I suggest to keep the model in the library as it is similar to `TwoPortHeatMassExchanger` and libraries the are based on `Annex60` are using it, for example in `Buildings.Fluid.Chillers.Carnot`.

To avoid breaking the model, a regression test needs to be added.

**Comment by mwetter** [comment]
If `Carnot` where to be moved to `Annex60`, it should be called `Carnot_y`.

All should comment whether this should be moved to the `Annex60` library.

**Comment by thorade** [comment]
Is this related to https://github.com/iea-annex60/modelica-annex60/issues/223 ??

**Comment by mwetter** [comment]
#223 is much bigger as its main purpose is to model an actual heat pump, whereas the Carnot model is idealized and meant for applications where no data of the heat pump is available, e.g., it is solely based on thermodynamics 2nd law, plus an efficiency correction that optionally takes the load as an input.

**Comment by damienpicard** [comment]
According to me, Annex60 could benefit of having the `Buildings.Fluid.Chillers.Carnot` model. I've revised the model and I've listed my comments in https://github.com/lbl-srg/modelica-buildings/issues/471. Once these comments are adressed and if everybody agrees, the Carnot model can be added.

**Comment by damienpicard** [comment]
As discussed in lbl-srg/modelica-buildings/issues/471, I did the following changes:
. Add a Carnot heat pump, and rename these models to Carnot_y (similarly than for the heater/cooler) to avoid a clash in names.
. remove actualStream in computing the states that are used to compute the Carnot efficiency.

I also added the example from the building library and i've updated the reference result.

I've pushed the changes on iea-annex60/modelica-annex60/tree/issue353_addCarnot_y

**Comment by mwetter** [comment]
@damienpicard 
I will also integrate the `Chiller.Carnot_TEva`, `HeatPumps.Carnot_TCon` and `HeatPumps.Carnot_y`.

I will also correct the COP computation so that the useful heat is the heat of the evaporator for the chiller, and the heat of the condenser for the heat pump.

To eliminate code duplication, I will refactor that `Chiller.Carnot_y` so that it uses a base class that can also be shared by `HeatPump.Carnot_y`, as is done for `Chiller.Carnot_TEva` and `HeatPumps.Carnot_TCon`.

**Comment by mwetter** [comment]
The above models have been integrated and documented. The following still needs to be done:

-  [ ] Review the examples and validation cases, and make sure P, QCon_flow and QEva_flow are plotted.
- [ ] Add validation cases in which the evaporator or condenser heat flow rate are limited.
- [ ] Add validation cases in which the evaporator temperature is higher than the condenser temperature to see whether the model behaves reasonably if it gets into this domain.

**Comment by damienpicard** [comment]
@mwetter notice that `Annex60.Fluid.Interfaces.FourPortHeatMassExchanger` is still not used in the `Annex60` library, as the implementation of the the `Carnot` model extends now `PartialFourPortInterface` instead of `FourPortHeatMassExchanger`.

**Comment by mwetter** [comment]
Note from Corsica meeting: Michael to ensure that the model is used in a regression test in `Annex60`, and then we keep it in the library for release 1.0.
