### ISSUE TITLE
numerical Jacobians in Airflow package

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#359]
The following scripts generate numerical Jacobians:
```
Resources/Scripts/Dymola/Airflow/Multizone/Examples/OneRoom.mos
Resources/Scripts/Dymola/Airflow/Multizone/Examples/ChimneyShaftNoVolume.mos
```
The models need to be analysed and changes made to allow symbolic expressions for the Jacobian.

**Comment by Mathadon** [comment]
I need to pull `BuildingsPy` before looking at this.
