### ISSUE TITLE
Three way valve has leakage parameter equal to 0

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#363]
This is not a valid value. The model correctly does not start due to an assert.
The leakage value should be changed to the same value as the two-way valve.
Because the model does not start without overwriting this value, this change in parameter assignment is backwards compatible and does not change any other models that run.

The problematic code is at
https://github.com/iea-annex60/modelica-annex60/blob/master/Annex60/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo#L49

**Comment by Mathadon** [comment]
fixed
