### ISSUE TITLE
JModelica error when dp_nominal=0

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#375]
JModelica produces the following error when dp_nominal = 0:
```
Error: in file 'path/IDEAS/Fluid/BaseClasses/PartialResistance.mo':
Semantic error at line 5, column 16:
  The attribute nominal for the variable dp is set to dp_nominal_pos, evaluating to 0.0. A nominal value of zero is not meaningful. Please set the nominal value to the expected magnitude of the variable.
```
the reason is that `dp_nominal = 0` when we want `computeFlowResistance=false`.

A workaround would be to set: `dp_nominal_pos = if abs(dp_nominal)>0 then abs(dp_nominal) else 1 ` instead of `dp_nominal_pos = abs(dp_nominal)`.

Do we want to merge this into Annex60?

**Comment by mwetter** [comment]
Yes, this would be good to merge into the Annex60 repository.

**Comment by Mathadon** [comment]
I'll need to look into it further since the proposed solution produces other problems.

**Comment by Mathadon** [comment]
I'm not using JModelica any time soon so I won't fix this. Do we close this issue or leave it open?

**Comment by mwetter** [comment]
I will close this until we are working on JModelica regression tests.
