### ISSUE TITLE
TBlaSky in ReaderTMY3

### ISSUE THREAD

**Issue by mlauster** [iea-annex60/modelica-annex60#377]
TBlaSky is calculated in ReaderTMY3 but is not an output. However, it would be helpful to have TBlaSky for radiation calculations.

In addition, check fails if TBlaSkySou is set to Parameter:

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/11814279/28efe6b2-a346-11e5-9bce-2c6fe08bff3c.png)

**Comment by mwetter** [comment]
@mlauster I mistakenly pushed the fix for this issue to the `master` instead of a development branch. The commit is https://github.com/iea-annex60/modelica-annex60/commit/187956ce680fc1d7594de13af7a6860118578ab4
Can you please verify whether this addresses your issue. All unit tests work fine.

**Comment by mlauster** [comment]
Everything looks good so far. Both problems have been solved. Thanks!
