### ISSUE TITLE
FlowControlled movers with correct power computations

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#395]
I need a mover that sets the pressure head of a fan, but that still computes the electrical power consumption using similarity laws. This is currently not supported. I had another look at how this could be implemented and I think a fairly simple solution exists. To implement it properly it would however be best to merge `Annex60.Fluid.Movers.BaseClasses.SpeedControlled` with `Buildings.Fluid.Movers.BaseClasses.FlowControlled` since `Annex60.Fluid.Movers.FlowControlled_dp` and `Annex60.Fluid.Movers.SpeedControlled_Nrpm` would use the same equation.

A short outline of what would need to change to have an implementation for `FlowControlled_dp` that extends from `Buildings.Fluid.Movers.BaseClasses.SpeedControlled`:

```
r_N = y_actual;
```
should be conditionally removed.

We should add a RealInput `dp_in` for setting the pressure head. This head should be used such that `dpMac.y=dp_in`. Finally one equation should be added: `dpMachine=dp_in`.

Dymola can then compute the value of `r_N` using the existing equation:
```
dpMachine = cha.pressure(per=pCur3, V_flow=VMachine_flow, r_N=r_N,
                                                VDelta_flow=VDelta_flow, dpDelta=dpDelta, V_flow_max=V_flow_max, dpMax=dpMax,
                                                delta=delta, d=preDer3, cBar=cBar, kRes=kRes);
```
This leads to a non-linear algebraic loop with one variable.
In case of a very simple pump we do not want the overhead of this computation, but we should be able to remove the computation conditionally if the user does not need to know the electrical power consumption. Note that the non-linear algebraic loop will always be of size 1 such that the computational overhead should be limited.

I like the idea of integrating the partials and adding the functionality of computing the electrical power accurately, but it may require some work to get this implemented properly, so I wanted to hear your thoughts on this first..? Otherwise I'll implement it in a quick-and-dirty way since I do need it.

**Comment by mwetter** [comment]
@Mathadon : I suggest you use the quick-and-dirty way for your project as this sounds like a larger reformulation if you need to change the base classes and ensure that the equation you need to invert always has a unique solution. It would probably take a while until this is properly reviewed as I have quite a backlog

**Comment by Mathadon** [comment]
Okay, will do!
