### ISSUE TITLE
Annex60.Fluid.Infiltration

### ISSUE THREAD

**Issue by rubenbaetens** [iea-annex60/modelica-annex60#402]
While making some new models, something striked me.

In `Annex60.Fluid`, there is a wide variety of models. Some models are generic and are valid for both liquids such as water as well as gases such as air (e.g. a `FlowControl` can both be a fan and a pump). Some are very specific, such as `IdealMotor` and `StorageTank`.

As such, i was wondering if it wouldn't be more natural that the models that are now in `Annex60.Airflow` are actually just a library in `Annex60.Fluid` ? For me it actually feels much more natural. Especially because all `Airflow.BaseClasses` extend from the `Fluid.BaseClasses`. Additionally, it feels weird to have a package, which only contains another package and nothing else (not only in `Annex60` but also in `IDEAS` and the `Buildings` library at this moment, i didn't check the others).

Almost all multizone airflow models date back to the COMIS model (LBNL, 1988) and its successors develop in Annex 20 and Annex 23. Here, COMIS is an acronym for 'Conjunction of Multizone Infiltration Specialist'. Having this in mind, i think it could be a clean solution to have an `Annex60.Fluid.Infiltration` package: It clearly states what's in the package, and doesn't require any renaming of packages at the same level. Also the even older single zone AIDA model and the AIOLIS model use the letter i as abbreviation for Infiltration, so the naming would fit the IBPSA and ASHRAE history on multizone airflow models.

Think about it.

**Comment by mwetter** [comment]
The intent of the package was that at some point there will be
```
Airflow.Multizone
       .CFD
```
and I called it `Multizone` as most models are based on what is in the CONTAM multizone airflow and contaminant transport software. Eventually, it would be good to also have contaminant sources and deposition models in this package, at which point `Annex60.Fluid.Infiltration` would be a bad name. Also, `Annex60.Airflow.Multizone` would (to me) imply that there should also be `Annex60.Airflow.{Fan, Ducts, ...}` which brings us back to also having to have `Annex60.{Water.{Pumps, Pipes, ....}, Glycol.{Pumps, Pipes, ....}}`. But this would increase maintenance and work for documentation considerably and add one more layer as we will probably have
```
AirFlow.Fans.SpeedControlled_y 
  extends Fluid.Fans.SpeedControlled_y(redeclare Medium = Annex60.Medium.Air);
annotation(documentation(info=" copy_of_documentation "));
```


In view of this, I am voting for leaving as it is.

**Comment by rubenbaetens** [comment]
I don't really see the link between the argumentation(s) and the conclusion(s). We state that there is `Annex60.Airflow` because we intended at some point to (...) and this would imply that (...) but in fact we will nót because (...) asks too much maintenance. So eventually all reasons why there was originally a `Annex60.Airflow` are expired.

Note: Also models for contaminant sources could be valid for both air and water (e.g. legionella).

**Comment by mwetter** [comment]
@rubenbaetens : Thanks for pointing this out. I misstyped some package names and now edited the above post. Hopefully this is clear now.

**Comment by mwetter** [comment]
@rubenbaetens shall we close this?
