### ISSUE TITLE
Consider using Q-IDENT names for movers

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#428]
Currently, we have pump data such as
```
record Stratos30slash1to8 "Pump data for a Wilo Stratos 30/1-8 pump"
....
```

The ugly name `*slash*to*` is because 
```
record Stratos30/1-8 "Pump data for a Wilo Stratos 30/1-8 pump"
....
```
is not valid.

We could have used the more readable version
```
record 'Stratos30/1-8' "Pump data for a Wilo Stratos 30/1-8 pump"
...
```
Then, an instantiation would change from
```
parameter Data.Pumps.Wilo.Stratos80slash1to12 per "Pump performance data";
```
to
```
parameter Data.Pumps.Wilo.'Stratos80/1-12' per "Pump performance data";
````

This issue is to discuss whether we want to use the form `record 'Stratos30/1-8'` for `Annex60.Fluid.Movers.Data.Pumps.Wilo`.

**Comment by mwetter** [comment]
Based on Fridays' teleconference, this should not be an issue to support in IDA/ICE.

We still need to check if OpenModelica and JModelica can handle it.

**Comment by Mathadon** [comment]
Sounds like a good change!

**Comment by Mathadon** [comment]
I tried this a while back and my experience was that it's very weird to have these kind of names :p Also there was some practical problem but this I do not recall.
