### ISSUE TITLE
Annex60.Controls.Continuous.LimPID triggers events when it saturates

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#433]
`Annex60.Controls.Continuous.LimPID` triggers events when the output limiter becomes active.
This considerably slows down the simulation of `Buildings.Examples.DualFanDualDuct`, and probably of other models as well. These events can be avoided by setting `strict=true`.

The code that is affected by this change is in the limiter of the MSL, 
```
  if initial() and not limitsAtInit then
     y = u;
     assert(u >= uMin - 0.01*abs(uMin) and 
            u <= uMax + 0.01*abs(uMax),
           "Limiter: During initialization the limits have been ignored.\n"+
           "However, the result is that the input u is not within the required limits:\n"+
           "  u = " + String(u) + ", uMin = " + String(uMin) + ", uMax = " + String(uMax));
  elseif strict then
     y = smooth(0, noEvent(if u > uMax then uMax else if u < uMin then uMin else u));
  else
     y = smooth(0,if u > uMax then uMax else if u < uMin then uMin else u);
  end if;
```
This issue is to see if we should set `strict=true` as the default value.

Below is a chart that compares the number of events and the CPU time. Run 2 is with `strict=false` while run 3 is with `strict=true`.
![closedloop](https://cloud.githubusercontent.com/assets/1329080/13787119/d2346a98-ea97-11e5-8e0f-9f060aed16e9.png)

**Comment by Mathadon** [comment]
My overall experience is that this is indeed a better implementation.

**Comment by mwetter** [comment]
`strict=true` is the default in `Buildings 3.0.0`. I did not see any noticeable change in the regression tests.
