### ISSUE TITLE
Implementation of MassFlowSource

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#440]
The MassFlowSource model currently contains the following equation
```
sum(ports.m_flow) = -m_flow_in_internal;
```

while I would expect to have

```
for i in 1:nPorts loop
ports[i].m_flow = -m_flow_in_internal;
end for;
```

For me the current implementation is not intuitive since it does not behave like a boundary condition, but as a mixing volume. I therefore propose to change its implementation.

**Comment by mwetter** [comment]
That's the same implementation as is used in the Modelica Standard Library. Having a different functionality would be cause for wrong use.
Can't you simply make a vector of these sources if you need more than one?

**Comment by Mathadon** [comment]
That's what I do now, but it's counterintuitive in my opinion which is also a cause for wrong use. :p Anyway, if that's how MSL does it then that's fine by me too!

**Comment by mwetter** [comment]
I remember that this was also discussed in the MSL design many years ago, but (maybe unfortunately) this is what the model was designed to do.
