### ISSUE TITLE
redesign flow functions

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#444]
I have a proposal to redesign the flow function implementation. The idea is to use a block (or even a twoport?) instead of a function. This would have three advantages.

1)
Fixed coefficients can be precomputed inside the block. Right now this is not possible in functions since this removes the ability to inline the code inside the function. This leads to more operations and worse performance.

2)
Currently the options from_dp=true and from_dp=false lead to more complex code (if/else clauses). The same is true for homotopy initalisation and the option to linearise the pressure drop equations. This code is also duplicated in multiple components. Concentrating this code in one block would avoid this.

3)
Making a block would allow the addition of many more flow functions (such as 1) linear flow, 2) quadratic flow and 3) the new one including both quadratic and laminar flow), which can then be selected using an enumeration record.

Could be interesting?

**Comment by mwetter** [comment]
If this indeed leads to simpler and more efficient computation, then this would be good. Maybe it would be good to have an implementation for models where `k` is fixed and where `k` is variable, which is the reason that `m_flow_turbulent` is an input and hence some coefficients are computed each time.

Also, if you don't use functions, make sure that 1st and 2nd derivatives are computed analytically by dymola, openmodelica and jmodelica. This is why we currently provide functions for these. See also revision notes in `basicFlowFunction_m_flow_der`.

Regarding 3), there should not be an option with only quadratic flow as its derivative is infinite near the origin. Hence, declaring the exponent `n` and the option `linearized` suffices.

**Comment by marcusfuchs** [comment]
This would be interesting to test and see the advantages/disadvantages of both approaches. We'll have a conference call on the pipe model this week, maybe there is also some more interest in testing this.

**Comment by mwetter** [comment]
Closed, also because blocks do not allow the use of the `inverse` annotation.
