### ISSUE TITLE
Fluid.FixedResistances.Examples.SplitterFixedResistanceDpM used in doc but is not in library

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#451]
The package information of `Annex60.Fluid.FixedResistances` has a link to `Annex60.Fluid.FixedResistances.Examples.SplitterFixedResistanceDpM`, but this model is only in `Buildings`, not in `Annex60`.

The model should be either added to `Annex60` or removed from the documentation. As we use this model very often in `Buildings`, I suggest to add it. It is similar to the 3 way valves, except that it has in each flow leg a `FixedResistanceDpM` model.

@mlauster, @Mathadon, @thorade do you (speaking for your libraries) think this should be added, needs more discussion, or are you against adding it?

**Comment by Mathadon** [comment]
I suggest to add it. It could however be useful to provide default (zero) values for `dp_nominal` and I'm not sure if we want to add a fluid state in this component by default?

**Comment by mlauster** [comment]
Adding examples is always helpful in my opinion. I see no reasons against adding it.

**Comment by thorade** [comment]
Same here, no objections against adding this.
