### ISSUE TITLE
Annex60.Experimental.Benchmarks.AirFlow.Examples.MultipleFloorsVectors has various bugs

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#454]
@marcusfuchs 
Can you please remove the errors and warnings in
`Annex60.Experimental.Benchmarks.AirFlow.Examples.MultipleFloorsVectors`, such as
"missing 'each'" and "connect(port_a_bot, port_a_bot) connects the same connector instance"

See 
https://test.openmodelica.org/libraries/Annex60/files/Annex60.Experimental.Benchmarks.AirFlow.Examples.MultipleFloorsVectors.err

**Comment by marcusfuchs** [comment]
With Dymola FD01, even in pedantic mode, I do not get any warnings or errors with this model. But I will have a look with OM.
