### ISSUE TITLE
Bug in radiator implementation

### ISSUE THREAD

**Issue by rubenbaetens** [iea-annex60/modelica-annex60#459]
I have a case where the thermal response of the radiator is causing  problems. When i apply a mass-flow at 40°C to the radiator with 5 elements, the temperature of the 1st, 3rd and 5th element rise, while the temperature of the 2nd and 4th element drop.

![radiator](https://cloud.githubusercontent.com/assets/1235535/14491094/1cf2dc86-0177-11e6-9588-71e9b13ecb85.JPG)

**Comment by carlesRT** [comment]
Which model are you using? <code>RadiatorEN442_2</code> ? I cannot reproduce the error using <code>Radiator.Examples.RadiatorEN442_2</code>.

It looks like there is no inflow and each volume is connected to a different boundary condition (could you plot the BC too?

thanks!

**Comment by rubenbaetens** [comment]
I'm indeed using `RadiatorEN442_2`, there is inflow (and equal outflow) and all `vol` are of course connected to the same heatports (that's internal in the radiator model).

![radiator2](https://cloud.githubusercontent.com/assets/1235535/14492474/b852c166-017f-11e6-82bd-651e5b04a775.JPG)

**Comment by rubenbaetens** [comment]
The bug disappears when `allowFlowReversal = false`.

**Comment by Mathadon** [comment]
You're not using Euler integration, right?

**Comment by rubenbaetens** [comment]
It happens both in `Dassl` and `Lsodar` ...

**Comment by mwetter** [comment]
@rubenbaetens 
Can you please add the Dymola `simulate(...)` command and, if you use a model that is not in the library, also a total model so we can reproduce (or add on a branch a model that reproduces the error, which we can then fix and keep the model as part of the regression tests to make sure it won't appear again).

**Comment by Mathadon** [comment]
@rubenbaetens is this fixed by #469 ?

**Comment by rubenbaetens** [comment]
@Mathadon it could actually be caused by the same bug you solved for the embedded system, i'll test it.

**Comment by Mathadon** [comment]
@rubenbaetens any update on this?

**Comment by rubenbaetens** [comment]
@Mathadon The results appear when a component with `allowFlowReversal = false` is in the loop of the radiator, but flow reversal occurs. So it's not really a bug of the radiator model.
