### ISSUE TITLE
Add sensor for flow velocity?

### ISSUE THREAD

**Issue by marcusfuchs** [iea-annex60/modelica-annex60#471]
For some of our applications, it would be useful to show the flow velocity of the medium. Is there interest in having a flow velocity sensor in the library?

**Comment by mwetter** [comment]
Yes, I think that would be good to add.

**Comment by marcusfuchs** [comment]
Ok, I'll make a first implementation.

**Comment by marcusfuchs** [comment]
I added a first simple implementation based on the `VolumeFlowRate` sensor. I will try to verify the results before creating a pull request.
