### ISSUE TITLE
Duplicate model in Psychometrics?

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#475]
It seems as if `Annex60.Utilities.Psychrometrics.WetBul_pTX` and `Annex60.Utilities.Psychrometrics.TWetBul_TDryBulXi` are more or less identical models. Can we remove either of the two? I suggest the former.

**Comment by mwetter** [comment]
From my point of view, `Annex60.Utilities.Psychrometrics.WetBul_pTX` can be deleted as all computations can also be done using `Annex60.Utilities.Psychrometrics.TWetBul_TDryBulXi`.
The only capability that `Annex60.Utilities.Psychrometrics.TWetBul_TDryBulXi` adds is to output `X` at the wet bulb temperature, which can also be computed using `X_pTphi`.

@thorade , @mlauster : Is UdK Berlin and Aachen OK with removing `Annex60.Utilities.Psychrometrics.WetBul_pTX`? If not, then the fix of #474 also needs to be applied to this model.

**Comment by mwetter** [comment]
@thorade , @mlauster 
Can you please comment on this so we can process the issue.

**Comment by mlauster** [comment]
Removing should be fine for Aachen.

**Comment by thorade** [comment]
Removing one of the two is fine for UdK.
