### ISSUE TITLE
Add glycol-water to medium with adaptable procentage

### ISSUE THREAD

**Issue by damienpicard** [iea-annex60/modelica-annex60#478]
As we might add my borefield model to the Annex-60 library, it would be good to also add a new media for the typical water-glycol solution used in borefield with parameteric concentration. Does anyone have such a model?

**Comment by mwetter** [comment]
@damienpicard:

I close this ticket to move the discussion to https://github.com/iea-annex60/modelica-annex60/issues/25
I agree that having such a medium is needed.
