### ISSUE TITLE
Documentation - water with temperature-dependent density

### ISSUE THREAD

**Issue by carlesRT** [iea-annex60/modelica-annex60#487]
I think section **Limitations**  <code>Specific heat capacity, thermal conductivity and viscosity are constant. Water is modeled as an incompressible liquid. There are no phase changes. </code> is wrong.

Dynamic Viscosity is defined with 
<code>eta := density(state)*kinematicViscosity(state.T);</code>  

and the kinematic Viscosity with 
<code>if T < 278.15 then -(4.63023776563e-08)*T + 1.44011135763e-05
  else 
    1.0e-6*Modelica.Math.exp(
      -(7.22111000000000e-7)*T^3 + 0.000809102858950000*T^2
      - 0.312920238272193*T + 40.4003044106506));</code>

It was probably copied from <code>Media.Water</code>. In case I did not missunderstood the code I would be good to correct the docu and add a plot (viscosity against T)

**Comment by mwetter** [comment]
@carlesRT 
You are right about the error in the documentation. It would be great if you can make a pull request against the branch `issue487_waterDocumentation`
