### ISSUE TITLE
JModelica errors?

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#488]
I get the following errors in JModelica when trying to compile one of my models:

```
Compliance error at line 276, column 23, in file '/media/psf/Home/Documents/Software/Annex60-git/Annex60/Fluid/Movers/BaseClasses/FlowMachineInterface.mo':
  minimumLength with higher than parameter variability is not supported
Compliance error at line 277, column 27, in file '/media/psf/Home/Documents/Software/Annex60-git/Annex60/Fluid/Movers/BaseClasses/FlowMachineInterface.mo':
  significantDigits with higher than parameter variability is not supported
```

I'm not sure how to deal with this. Is this a known issue?

Edit: I'm running r8340 so I'll try to update first.

**Comment by carlesRT** [comment]
First time I see this error.... But it reminds me the error one gets when a variable is assigned to a parameter. 
<code>The variability of the definition equation: </code> parameter = variabel <code> is higher than the declared variability of the variables</code>.

**Comment by Mathadon** [comment]
I installed the latest JModelica and now I get a different issue. So I'm not sure if this is solved, but I'll close the issue for now.

**Comment by mwetter** [comment]
@Mathadon The `.Movers` package does not yet work in JModelica because of the way it uses the performance records. Modelon will correct the compiler accordingly.

**Comment by Mathadon** [comment]
That's probably it then. 
Do you know more or less when this feature will be added?

**Comment by mwetter** [comment]
Sometime this calendar year, hopefully within a couple of months.
