### ISSUE TITLE
Refactor to export weather resource file as FMU

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#489]
This issue should refactor the weather data reader to allow the export of models which contain weather file as FMUs.

Todo:
- [x] Merge this to the master branch.

**Comment by mwetter** [comment]
@tsnouidui: I created branch `issue489_weatherFMU`

**Comment by mwetter** [comment]
@tsnouidui Please correct `BoundaryConditions/WeatherData/BaseClasses/getAbsolutePath.mo` which differs between this development branch and the `master` of `Buildings`

**Comment by tsnouidui** [comment]
@mwetter I made a local diff between this branch and the master of Buildings and got

< within Annex60.BoundaryConditions.WeatherData.BaseClasses;
---
> within Buildings.BoundaryConditions.WeatherData.BaseClasses;
40c40
< Now the function works from any directory as long as the <code>Annex60</code> library
---
> Now the function works from any directory as long as the <code>Buildings</code> library

Do you get/expect something different?

**Comment by mwetter** [comment]
Sorry, my local copy used the old cached state of the branch. The files are identical (except for the top-package name).

**Comment by mwetter** [comment]
This is now on the `master`.
