### ISSUE TITLE
LimPID with integrator reset

### ISSUE THREAD

**Issue by PMehrfeld** [iea-annex60/modelica-annex60#494]
I want to enhance `Annex60.Controls.Continuous.LimPID`. When a boolean input becomes true, the integrator should be reset.
The problem is easy to solve as long as you are not in pedantic mode.
But to satisfy pedantic criteria I can only see the solution to copy the whole source code of `Modelica.Blocks.Continuous.LimPID` instead of extending it. Because then the integrator can be replaced by an own integrator model including a boolean input to reset/reinit() the output `y.`

I will show the two possibilities in a new fork.

**Comment by PMehrfeld** [comment]
It would be nice to get some feedback about the two options you can see in my fork: [issue494_resetIntPID](https://github.com/PMehrfeld/modelica-annex60/tree/issue494_resetIntPID)

So, what do you think is the best?
Option a) Leave LimPID as extension from standard library, but check in pedantic mode leads to erros.
Option b) Duplicate LimPID form standard library and create own integrator.
Option c) Neither a) nor b) and let everyone model this by himself/herself if someone need a reset of the integrator.
Option d) A better modelling approach than a) that will also meet the requirements of pedantic mode.

It would be nice to receive some feedback.

**Comment by Mathadon** [comment]
Hi!
I did not check all of your code but I think b) would be best as long as the additional inputs / complexity can be disabled by default such that the default implementation stays the same. 

The question arises however if we should do 

```
reinit(y,y_inint)
```

or 

```
reinit(y, something else)
```

c) is an option as well since we do not want to overload the user with complex options. Good documentation should however be sufficient to deal with this.

**Comment by PMehrfeld** [comment]
Thanks a lot for your recommendations!

I now decided to choose Option b) and use the edge() function. Also you can choose the value to reinit with.
I hope the documentation is detailled enough.
