### ISSUE TITLE
Parametrize tau of sensors

### ISSUE THREAD

**Issue by rubenbaetens** [iea-annex60/modelica-annex60#496]
All sensor models have a parameter `tau` for the time-constant of the sensor. Would it be interesting to parametrize the default value based on `m_flow_nominal` and `media.rho` ?

**Comment by Mathadon** [comment]
You'd need an indication of the mass/volume of the sensor. Defining this mass is equivalent to setting tau directly, while tau is easier to interpret imo. So I don't see the added value :)

**Comment by mwetter** [comment]
I agree with @Mathadon. Also, `tau` is an idealization, pretending that the sensor dynamics depends on `media.rho` would not be good if used with air, as the main dynamics is probably governed by the inertia of the metal, not the air. Hence, I will close this. Feel free to reopen if you disagree.
