### ISSUE TITLE
Default values for Carnot chiller/heat pumps can violate 2nd law

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#497]
The `Carnot_*` heat pumps and chillers use as the default values for computing the Carnot effectiveness inlet and outlet temperatures for the condenser or evaporator.

At small temperature lifts, using inlet temperatures only can lead to a computation of the Carnot efficiency that is higher than the actual Carnot efficiency.

In a model, we observed that for the situation of using the inlet temperatures _and_ having low lifts, the entropy generated by the chiller was negative, which is a violation of the 2nd law. Therefore, the default values should be changed to using the outlet temperatures, which is a more conservative assumption that leads to lower Carnot efficiencies, and ensures that the 2nd law is not violated.

**Comment by mwetter** [comment]
I added an entropy flow rate sensor that can be used for the validation. What remains to be done is
- [ ] Change the default values of the temperatures used to compute the Carnot efficiency to be the volume temperature or the `port_b` temperatures.
- [ ] Add validation tests that show that for small temperature lifts, the 2nd law is no longer violated.

**Comment by mwetter** [comment]
The plot below shows that for the chiller model in which the inlet temperatures are used to compute the Carnot efficiency (instance `chi_a`), if the temperature lift is small, entropy is generated which violates the second law. I therefore recommend:
- [ ] that the model is changed by removing the options of what temperature is used to compute the Carnot efficiency, and always use the outlet temperature.
- [ ] Update the regression tests accordingly for the new model.

![carnot_teva_2ndlaw](https://cloud.githubusercontent.com/assets/1329080/20457684/a436670c-ae4d-11e6-81a1-7b4c30db7faf.png)

**Comment by mwetter** [comment]
@mlauster , @thorade , @Mathadon 
Please let me know if you agree with the three proposed items above from Nov. 19. I will then implement the changes and make a pull request.

**Comment by Mathadon** [comment]
I agree.

Maybe `Annex60.Fluid.Types.EfficiencyInput` may be used in the new heat pump model. But I doubt it :)

**Comment by mlauster** [comment]
Sounds like a worthwhile improvement, no objections from Aachen side.

**Comment by thorade** [comment]
No objections, sounds reasonable.
