### ISSUE TITLE
Clean up equivalent air temperature calculations

### ISSUE THREAD

**Issue by mlauster** [iea-annex60/modelica-annex60#500]
In contrast to TRY weather data sets, TMY sets do not provide data about environmental radiation (which is not atmospheric radiation but in most cases exactly the same values). The `equivalentAirTemperature` models account for this by omitting the calculation parts given in VDI 6007-1 dealing with environmental radiation. When reviewing the models for integration in `AixLib`, I found some relicts of these calculations in the actual Annex60 models. I will withdraw these relicts (that lead to "correction" factors around 1).

**Comment by mlauster** [comment]
@mwetter, I removed some deprecated parameters from `equivalentAirTemperature` models and renamed one. This forces changing names and delete old parameters as well in model applications, so some kind of backwards incompatibility. Is this an issue and I should keep the old parameters and names? Or is the `Annex60` lib still in a phase where backwards incompatible changes can be accepted?

**Comment by mwetter** [comment]
@mlauster 
I am not yet concerned about backward incompatibility of `Annex60.ThermalZones` as we have not yet released it with `Buildings`. I don't know about the other libraries. In my view, it is more important to get `Annex60.ThermalZones` cleaned up to a state where we can avoid (or minimize) backward incompatible changes.

Once we switch to the IBPSA repository, we should have a backward incompatible maintenance branch in addition to the master.

**Comment by mlauster** [comment]
Still to do:
- [ ] Think about combining `EquivalentAirTemperature.VDI6007` and `EquivalentAirTemperature.VDI6007WithWindow` with option to handle windows separately. I'm not yet sure if this a good idea or not. Advantage would be that choosing this option on high-level model would be much easier. Disadvantage is that the weightfactors are handled differently in the models and the user would have to change them when enabling the option of separate windows. This is not really obvious and users might be confused.

**Comment by mlauster** [comment]
Decision made: I will leave it as it is (separate models), combining them would mean a lot of effort and a possibly dirty structure without having justifiable advantages.
