### ISSUE TITLE
MSL version 3.2.2

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#506]
Dymola 2017 uses MSL 3.2.2. Can we update the Annex 60 version number?

**Comment by mwetter** [comment]
Fine with LBL. We prefer to use dymola 2017 for the regression tests if that is fine with UdK, Aachen and Leuven.

**Comment by marcusfuchs** [comment]
At Aachen, we would also prefer to switch to Dymola 2017.

**Comment by Mathadon** [comment]
No objections -> I propose to proceed. Can we just update the version number or are there other changes that need to be made? 
If the unit tests need to be re-run I propose Michael does the update since my results or sometimes off by a fraction.

**Comment by thorade** [comment]
UdK is also using Dymola 2017 for a while.

**Comment by mwetter** [comment]
OK, I will update the MSL version and re-run the unit tests.
