### ISSUE TITLE
Additional water models for other temperature ranges (e.g. for district heating)?

### ISSUE THREAD

**Issue by marcusfuchs** [iea-annex60/modelica-annex60#511]
Today we had another conference call to discuss the development of the pipe model. One topic that came up was that the water model `Annex60.Media.Water` is not really a good fit for all district heating applications, in which temperatures may exceed the maximum allowed temperature and densities may differ significantly. 

Is there interest in including somewhere between 1 and a few more water models with the same complexity but different temperature ranges to the Annex 60 library? If not, alternatives would be to have a very small separate library for this or otherwise I also do not think that there would be objections to include this e.g. in AixLib. I personally already use such water implementations and could add the code.

**Comment by mwetter** [comment]
That would be OK to add in `Media.Specialized.Water.` I think you could just extend `Media.Water` and set some constants, and add regression tests so we cover it in our test suite.

**Comment by Mathadon** [comment]
Would it be sufficient to create a Medium that allows setting a different 'nominal temperature'? You could for instance choose to use medium properties at 80 degrees C instead of what we now have, such that this is a good approximation of water properties in the 60-100 degree range.
Or do the densities still vary too much then?

**Comment by marcusfuchs** [comment]
@Mathadon : I think it is a good suggestion to not fix the nominal temperature and add multiple models for different temperature ranges but allow setting this in one model by the user. I will have a look at how to implement this. 

>...such that this is a good approximation of water properties in the 60-100 degree range. Or do the densities still vary too much then?

As long as we go for constant density, I think we cannot be more accurate than this, because if the supply temperatures are around 100 °C and the return temperatures are around 60 °C, we would otherwise have to use two different media for supply and return network.

**Comment by marcusfuchs** [comment]
I implemented a first version in the branch `issue511_waterNominal`. In the new model `Annex60.Media.Specialized.WaterNominalCond` the user can set the constants `T_nominal` and `p_nominal`, based on which the constant water properties are calculated using the `IF97` water model functions.

I will continue to add examples and unit tests for this next week. In the meantime, any suggestions are of course welcome.

**Comment by mwetter** [comment]
@marcusfuchs
In 
```
extends Annex60.Media.Water(
```
please also add the value of temperature and pressure to the medium name. This way, Modelica will complain if components with different media will be connected, which I believe we want to avoid unless we analyze that thermodynamically nothing can go wrong by connecting two components with water with different `T_nominal` and `p_nominal`.

Your package is also one level too high in the hierarchy. It should be parallel to `Annex60.Media.Specialized.Water.TemperatureDependentDensity`.

Also, I suggest you call it `Annex60.Media.Specialized.Water.NominalCondition` or `Annex60.Media.Specialized.Water.ConstantProperties_pT` (as we use in thermodynamic function calls, and in some models of the psychrometric package, to indicate what is input or here a constant as it is a package).

**Comment by marcusfuchs** [comment]
@mwetter 
Thank you for the comments. I think I adressed most of it and would be almost ready to create a pull request. Only open point is this:

>In `extends Annex60.Media.Water(` please also add the value of temperature and pressure to the medium name.

Are you referring to what is now line 40 of `Annex60.Media.Specialized.Water.ConstantProperties_pT`? I would not be quite sure how to add the values to the medium name in that case.

**Comment by bramvdh91** [comment]
I would propose something like 
```
 extends Annex60.Media.Water(
    mediumName="Water_p" + String(p_nominal) + "_T" + String(T_nominal),
    ...
``` 
which concatenates the value of the pressure and temperature with the medium name. I cannot check if this takes effect on the medium on declaration, but it doesn't seem to produce any errors.

**Comment by marcusfuchs** [comment]
Ah, thanks for this suggestion, I had misunderstood Michael's comment. I can of course add this.

**Comment by mwetter** [comment]
@marcusfuchs , @bramvdh91 : Yes, that is what I meant.

**Comment by marcusfuchs** [comment]
I went with 
```
extends Annex60.Media.Water(
  mediumName="ConstantPropertyWater(p="+String(p_nominal)+",T="+String(T_nominal)+")",
```
