### ISSUE TITLE
Course regularisation in Annex60.BoundaryConditions.SolarIrradiation.BaseClasses.SkyClearness

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#521]
I'm updating IDEAS to Annex60 models for solar irradiance computations. In our unit tests I detected a change in results for Annex60.BoundaryConditions.SolarIrradiation.BaseClasses.SkyClearness. More specifically the value of  `skyCle` goes as low as 1 in our old implementation and now only as low as 1.1. This seems to be because of the regularisation.

```
skyCle =  smooth(1,
    if (HGloHor < Modelica.Constants.small)
      then 
        1
      else 
       IDEAS.Utilities.Math.Functions.smoothLimit(
        x = (HGloHor/IDEAS.Utilities.Math.Functions.smoothMax(
                       x1 = HDifHor,
                       x2 = 1e-4,
                       deltaX = 1e-5) + tmp1)/(1 + tmp1),
        l = 1,
        u = 8,
        deltaX = 0.1));
```
Since `deltaX=0.1` the actual lower limit is 1.1 instead of 1. This has a non-negligible impact on our unit tests. Therefore I propose the change deltaX to 0.01 or lower.

**Comment by mwetter** [comment]
@Mathadon This proposal is good. I will also change the regression test simulation period so that other values than the minimum sky clearness are computed.
