### ISSUE TITLE
invalid path in ReaderTMY3 documentation

### ISSUE THREAD

**Issue by mlauster** [iea-annex60/modelica-annex60#533]
The documentation of `BoundaryConditions.WeatherData.ReaderTMY3` contains a command to convert `.epw`-files to `.mos`-weatherfiles. The associated java archive is not part of Annex60 yet (it is part of Buildings), thus the command does not work. Should we integrate the archive into Annex60 or modify the documentation? It is not possible to link only to Buildings, the merge-script from BuildingsPy will change this path when merging into another library.

**Comment by mwetter** [comment]
I am fine with distributing the jar and java files with `Annex60` so that other library users also can convert the `epw` file.

**Comment by mlauster** [comment]
Would be nice to have!

**Comment by mwetter** [comment]
@thorade , @Mathadon 
Could you please let me know if it is fine for your libraries if I include the java code
```
Buildings/Resources/src/convertEPW/*
Buildings/Resources/bin/ConvertWeatherData.jar
```

**Comment by thorade** [comment]
Fine for me!

**Comment by Mathadon** [comment]
Ok!
