### ISSUE TITLE
Flow system examples for Corsica

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#536]
This issue is to discuss some examples that could be added to the Annex 60 library that further demonstrate the use of options such as 
- energyDynamics
- filteredSpeed
- allowFlowReversal
- from_dp

etc

**Comment by Mathadon** [comment]
We can merge this after feedback from the course.

**Comment by Mathadon** [comment]
See examples in `Annex60.Fluid.Examples.FlowSystem` on https://github.com/iea-annex60/modelica-annex60/tree/issue536_corsica 

Do we need unit tests for (all) of these? It could be useful to detect when statistics change, but it takes a long time to compile the models.

**Comment by mwetter** [comment]
@Mathadon : Yes, we want unit tests, otherwise we may ship broken code without realizing it. (Also, right now, I get
```
translateModel("Annex60.Fluid.Examples.FlowSystem.Simplified6");
 = false
```
as the models uses types from `Buildings`.
