### ISSUE TITLE
Dynamics section in documentation / style guide

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#537]
In the style guide (https://github.com/iea-annex60/modelica-annex60/wiki/Style-Guide) we suggest some titles to be used in the documentation. I propose to add a section about the dynamics of the model: which states does that model contain, what are typical time constants and what parameters may be used to influence those states. This should facilitate proper use of those models.

Open question: should all this info be included in partials as well? This would lead to more overhead for us and to duplicate documentation. Or should we only include it in the user guide?

**Comment by mwetter** [comment]
Adding a section about the states is fine. I suggest not to add in in the partial classes as a model that extends from a partial class may overwrite the logic, and hence it may be confusing from the user to see two different information.

**Comment by Mathadon** [comment]
I added 

```
       <h4>Dynamics</h4>
       <p>
       Describe which states/dynamics are present in the model
       and which parameters may be used to influence them.
       This need not be added in partials.
       </p>
```

in the style guide. I'll try to add this section when working on the relevant models.

@mwetter can you close this if you agree with the change?

**Comment by mwetter** [comment]
@Mathadon I made minor rewording and will close this issue.
