### ISSUE TITLE
Text in icon of Annex60.Fluid.FixedResistances.FixedResistanceDpM

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#556]
The icon of Annex60.Fluid.FixedResistances.FixedResistanceDpM contains text labels for `dp_nominal` and `m_flow_nominal`. In my opinion they are not instructive and they clutter the graphical view. In addition they are often not readable. I propose to remove these labels.

**Comment by mwetter** [comment]
@Mathadon Please remove them from the icon layer. @marcusfuchs also agrees.
