### ISSUE TITLE
Model name in Annex60.Fluid.Interfaces.PartialTwoPort

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#557]
`Annex60.Fluid.Interfaces.PartialTwoPort` contains a label in the icon for the model name by default.
This may clutter the GUI, which can be annoying when making slides etc. Can we make this label conditional?

**Comment by mwetter** [comment]
Does it interfere with other drawing elements in your model or do you simply want to remove it when making slides. If it is the first, then feel free to make this label conditional (and show it by default), if it is the second, then I suggest you export the graphic as svg, remove labels in inkscape, and then use this vector graphics in your presentations.

**Comment by Mathadon** [comment]
Second case applies and it's a good suggestion, thanks.
