### ISSUE TITLE
Assert in MixingVolume and EnthalpyFlowRate is problematic

### ISSUE THREAD

**Issue by agnesramle** [iea-annex60/modelica-annex60#564]
In the models
*  Annex60.Fluid.MixingVolumes.Validation.MixingVolume
*  Annex60.Fluid.Sensors.Examples.EnthalpyFlowRate
the assert
assert(noEvent(abs(assertEquality.u1 - assertEquality1.u2) < assertEquality1.threShold) is problematic since 
assertEquality.u1 and assertEquality.u2 depends heavily on the state variables
vol1.dynBal.U
vol2.dynBal.U
vol.m
The global Jacobian is approximated and therefore it is not possible to gain the required accuracy. Suggestion is to remove the assert and do the check in the post-processing of the simulation instead. 
It may also be possible to change the assertion level to warning.

**Comment by mwetter** [comment]
There are various other files that have a similar problem and will be fixed on this branch.

**Comment by Mathadon** [comment]
@agnesramle would it be an option to increase the threshold? To what level should it be increased then?

**Comment by agnesramle** [comment]
@Mathadon I'm not sure it would work. Of course it depends on the threshold, but in that case I would use a relative tolerance instead of the current absolute. For example, we recieved

<AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 1.64001e-007&#10;  u1         = 35861.7&#10;  u2         = 35930.8&#10;  abs(u1-u2) = 69.0548&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <Warning category="warning">Evaluating the derivatives failed at <value name="t">       1.6400110748819155E-007</value>, retrying with restored values.</Warning>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 1.64001e-007&#10;  u1         = 35861.7&#10;  u2         = 35930.8&#10;  abs(u1-u2) = 69.0548&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error] <Error category="error">Evaluating the derivatives failed at <value name="t">       1.6400110748819155E-007</value></Error>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 1.64001e-007&#10;  u1         = 35861.7&#10;  u2         = 35792.5&#10;  abs(u1-u2) = 69.1881&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <Warning category="warning">Evaluating the derivatives failed at <value name="t">       1.6400110748819155E-007</value>, retrying with restored values.</Warning>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 1.64001e-007&#10;  u1         = 35861.7&#10;  u2         = 35792.5&#10;  abs(u1-u2) = 69.1881&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error] <Error category="error">Evaluating the derivatives failed at <value name="t">       1.6400110748819155E-007</value></Error>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 4.10003e-008&#10;  u1         = 14226&#10;  u2         = 14023.5&#10;  abs(u1-u2) = 202.483&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <Warning category="warning">Evaluating the derivatives failed at <value name="t">       4.1000276872047887E-008</value>, retrying with restored values.</Warning>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 4.10003e-008&#10;  u1         = 14226&#10;  u2         = 14023.5&#10;  abs(u1-u2) = 202.483&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error] <Error category="error">Evaluating the derivatives failed at <value name="t">       4.1000276872047887E-008</value></Error>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 1.02501e-008&#10;  u1         = 3687.77&#10;  u2         = 3461.3&#10;  abs(u1-u2) = 226.473&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <Warning category="warning">Evaluating the derivatives failed at <value name="t">       1.0250069218011972E-008</value>, retrying with restored values.</Warning>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 1.02501e-008&#10;  u1         = 3687.77&#10;  u2         = 3461.3&#10;  abs(u1-u2) = 226.473&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error] <Error category="error">Evaluating the derivatives failed at <value name="t">       1.0250069218011972E-008</value></Error>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 2.56252e-009&#10;  u1         = 923.993&#10;  u2         = 696.077&#10;  abs(u1-u2) = 227.916&#10;  threShold  = 0.01"</value></AssertionError>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <Warning category="warning">Evaluating the derivatives failed at <value name="t">       2.5625173045029929E-009</value>, retrying with restored values.</Warning>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <AssertionError category="warning"><value name="msg">"Inputs differ by more than threShold&#10;  time       = 2.56252e-009&#10;  u1         = 923.993&#10;  u2         = 696.077&#10;  abs(u1-u2) = 227.916&#10;  threShold  = 0.01"</value></AssertionError>

when simulating Annex60.Fluid.MixingVolumes.Validation.MixingVolume with jmodelica [https://jenkins.jmodelica.org/job/Annex60-Compliance-Simulate/1143/artifact/diag/0f35038e_simulate.html].

**Comment by Mathadon** [comment]
It's odd that the 'error' increases when the 'step time' shrinks? 

You mention that the Jacobian is approximated. Is this the Jacobian of the integrator or of the Newton solver for an algebraic loop? If it's the integrator, what integrator do you use (CVode?) and using which tolerance?

Thanks!

**Comment by agnesramle** [comment]
It is the Jacobian of the integrator. CVode is used with a tolerance of 1e-6.

**Comment by Mathadon** [comment]
So the desired tolerance is not obtained? I suppose this is a 'transient' effect while the Jacobian approximation is improved?

**Comment by chria** [comment]
Hi,

I believe there is a fundamental problem here. Am I correct in assuming that this is a check that the computed solution fulfills some property at each step? Some variables (dependent on different states) should be equal. If so, the problem with this is that when we solve the system using an external implicit integrator (CVode in our case) we end up with a nonlinear system which we solve using Newton. Now the Jacobian is approximated using finite difference which perturbs the states and when doing this, the above assert unfortunately is not relevant as this is not an accepted solution.  

Changing the threshold will not make it any better. Isn't this a verification that should be checked once the integrator is satisfied with the computed solution? Before the step/solution is accepted I believe the difference should not be checked as during the solution process it may/will be violated. But this does not mean that the assert will be violated in the computed solution (which should be verified afterwards).

Does this help?

Best
/Christian

**Comment by mwetter** [comment]
@chria 
From the Modelica specification:

> level = AssertionLevel.error: The current evaluation is aborted. The simulation may continue with another evaluation [e.g., with a shorter step-size, or by changing the values of iteration variables]. If the simulation is aborted, message indicates the cause of the error.

Because "the current evaluation is aborted", am I right that our use of `assert` in this context is wrong? Our intended test is to check whether the *accepted solution* satisfies this test, but if the assert causes the evaluation of the model to be aborted during the iterative solution procedure, we would indeed need to removed this `assert` statement.

Could you please confirm that we need to remove the `assert` so that we can make the appropriate change in the library?

**Comment by Mathadon** [comment]
The computation verifies if the MSL and Annex60 implementations of a 'Mixing Volume' find the same solution, which they should for the considered problem. Both results are indeed a direct function of a state.

When perturbing the solution you should indeed not evaluate these asserts. I agree with Christian's analysis. 

This is probably something that should be 'fixed' in JModelica instead of in Annex 60.

**Comment by chria** [comment]
@mwetter

Yes, I believe it is used incorrectly in this case. Even if we are aborting the step (which we are), perturbing the state variables at that step to approximate the Jacobian will lead to the same problems (depending though on the current values of the states as the perturbation is based on this, among other things).

@mathadon

Yes, in this case it would be an option to not evaluate the asserts during the approximation but unfortunately it is not known (in the FMU) in which situation the equations are evaluated (Jacobian approximation, step computation, etc). In other cases though asserts are used to guard against a model being outside of a validity region (where it is not even possible to evaluate the equations) and in this case they should be included during the approximation.

I agree it would be useful to extend the usage of the asserts so that it would be possible to specify that this assert should only be evaluated once the integrator has accepted a step.

Best
/Christian

**Comment by Mathadon** [comment]
@chria I'll check the Modelica trac to suggest this functionality.
I suppose that adding such functionality to the FMU is not possible given the constraints imposed by the FMI standard?

Out of curiosity: is there a timeline for computing (part of) the Jacobian analytically?

**Comment by chria** [comment]
@Mathadon Ok great. Adding it to the FMU is currently not possible, at least for FMI version 1.0. unfortunately. Regarding the Jacobian I'm not sure, sorry.

**Comment by mwetter** [comment]
@agnesramle , @chria : Thanks for your feedback. The models are now fixed on the master branch of the Annex60 and Buildings libraries.

**Comment by mwetter** [comment]
Closed issue because this is fixed on the master branch.

**Comment by Mathadon** [comment]
Ticket: https://trac.modelica.org/Modelica/ticket/2110#ticket
