### ISSUE TITLE
PrescribedHeatFlow parameters in ReducedOrder package

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#572]
This package has various models that assign code such as
```
Modelica.Thermal.HeatTransfer.Sources.PrescribedHeatFlow convHeatSol(
    final T_ref=T_start)
```
I don't know why this is done, as the default is `alpha=0`, and hence the value of `T_ref` does not matter.

This issue is to revise the model, and also check whether setting `final alpha=0` simplifies the equations as it did for https://github.com/iea-annex60/modelica-annex60/issues/570

**Comment by mlauster** [comment]
@mwetter, I changed that in he corresponding RC-model. There are still assignments of start temperatures to prescribedHeatFlow elements in the validation cases, even if alpha=0. Shall I change that as well? We should rerun the regression tests then just to make sure to not break the validation.

**Comment by mwetter** [comment]
@mlauster If `final alpha=0`, I would remove the `T_ref` as they are not used anyway.
