### ISSUE TITLE
Inlining Annex60.Utilities.Math.Functions.regStep

### ISSUE THREAD

**Issue by tsnouidui** [iea-annex60/modelica-annex60#579]
This issue is to test whether inlining the `Annex60.Utilities.Math.Functions.regStep` function will decrease translation and simulaton time of Modelica models in JModelica.

**Comment by Mathadon** [comment]
I suppose you know this, but you may debug translation time somewhat easier by defining `compiler_log_level = 'd'` in `compile_fmu()`.

**Comment by tsnouidui** [comment]
Thanks!

**Comment by tsnouidui** [comment]
Inlining `Annex60.Utilities.Math.Functions.regStep` does not improve compilation/simulation time.
