### ISSUE TITLE
Add Buildings.Fluid.Sources.Outside to Annex60

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#588]
This model is similar to `Boundary_pT`, except that it has a weather data bus. I suggest to add this to the `Annex60` library. We always use this when we model an air-based system as it add the humidity as obtained from the weather data bus.

@thorade , @Mathadon , @mlauster : Is this OK to be added? We will also use it for https://github.com/iea-annex60/modelica-annex60/issues/472, for which I added a work-around to get the mass fraction into the fluid flow system

**Comment by Mathadon** [comment]
@mwetter for me this is ok. In the current form we will probably not use it in IDEAS since it requires a manual connection between the component and the data reader, which is inconvenient. It may of course be interesting to work towards something similar to a `SimInfoMager` in Annex 60?

**Comment by thorade** [comment]
OK for @UdK-VPT

**Comment by mlauster** [comment]
No objections from Aachen.

**Comment by Mathadon** [comment]
@mwetter I'm confused since we already have `Annex60.Fluid.Sources.BaseClasses.Outside`?

Can this be closed?

**Comment by mwetter** [comment]
It cannot be closed as `Annex60.Fluid.Sources.BaseClasses.Outside` is `partial`. See
`Buildings/Fluid/Sources/Outside.mo` which needs to be ported to `Annex60` and used for #472.

**Comment by Mathadon** [comment]
fixed in #627
