### ISSUE TITLE
Thermostatic radiator valve model

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#589]
@mwetter @mlauster @marcusfuchs @thorade 
First of all, why do all your names start with M? 

Secondly, do any of you have a decent model of a thermostatic radiator knob?

![thermostaatkraan](https://cloud.githubusercontent.com/assets/5970879/20244225/2d952044-a979-11e6-93fb-19ce8a642782.jpg)

I.e. a model that generates a control signal such that it can be combined with `Annex60.Fluid.Actuators.Valves.TwoWayLinear`.

**Comment by mlauster** [comment]
@Mathadon, we have a Thermostatic Head model in our internal, "messy" libraries, which we are currently discussing to integrate into `AixLib`, see https://github.com/RWTH-EBC/AixLib/issues/182. If this is of interest for you, we could see how fast we can get a first version into an `AixLib` branch.

**Comment by Mathadon** [comment]
Does it compute a valve set point using a temperature measurement? If so then it could be of interest! Otherwise it's probably faster to make a new model myself :)

**Comment by thorade** [comment]
As far as I know we do not yet have a thermostatic vavle model in BuildingSystems.

**Comment by mwetter** [comment]
We don't have a specific model for a thermostatic radiator knob. We usually just use a P controller and connect it to the room air and/or radiative temperature.

**Comment by mlauster** [comment]
I think so, let me check that! This week is a bit busy, maybe I can push it next week

**Comment by Mathadon** [comment]
It was a bit urgent so I made a model already, but I can have a look at it if you manage the push it :)

**Comment by mlauster** [comment]
Hm, let's see, yours will be faster anyway. :)

**Comment by Mathadon** [comment]
actually that reminds me that there's a parameter division that I should eliminate!

**Comment by mwetter** [comment]
Closed for now. Please reopen if there are plans to integrate the model in Annex60.
