### ISSUE TITLE
Bug in valve model (phi > 0)

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#592]
The fix of https://github.com/iea-annex60/modelica-annex60/issues/558 is not working. The issue is that `phi > 0` does not allow for numerical noise.

Running 
```
Buildings/Resources/Scripts/Dymola/Examples/HydronicHeating/TwoRoomsWithStorage.mos
```
leads to
```
val1.phi > 0
The following error was detected at time: 26210.50904559367
Valve control signal needs to be bigger than zero, received phi = -7.37661e-15
HandleRoot:HandleRoot
Integration terminated unsuccesfully at T = 26165.1
```
The test should be relaxed. As we guard against user errors, I suggest to test the assertion for `phi > -1.2` which should suffice.

**Comment by Mathadon** [comment]
Shouldn't the valve leakage guard against numerical noise?

Why -1.2?

**Comment by mwetter** [comment]
Why not -1.2? 
I selected a large value as JModelica may execute the FMU during the iterations, and during the solution procedure, some steps could be much farther away than just the numerical noise is. I would think that if a user uses the valve in the wrong context (e.g, with control signals between -1 and 1), he/she may quickly run into triggering this assert.

**Comment by Mathadon** [comment]
If the control signal is -1 then phi could for instance be ~-0.98 and not trigger the assert. So the slack is too large in my opinion. I'd go for -1e-3 or something and see if we get into trouble then?

**Comment by mwetter** [comment]
I meant `phi > -0.2`, rather than `-1.2`. I fixed it in the pull request.
I would not go as low as `-1E-3` because we don't know how much the solver steps away from the solution during the iteration, hence a larger value (`-0.2`) should be more robust, and likely catches the error that we observed from the user.

**Comment by Mathadon** [comment]
Still it makes more sense to me to fix any solver problems if/when they arise, rather than assuming that they may appear in some case. Especially if we now have the negative side effect that valves may be used as a pump unnoticed if not properly used by users. This may also cause bugs that are difficult to debug as we could see during the course. These may however still appear for -e-3 so maybe that's not really an argument.

If you insist then feel free to merge #593!

**Comment by mwetter** [comment]
It is not a solver problem, but rather an ambiguous part of the specification as it is not clear whether assertions are only tested on the accepted solution. In a FMU, there is no way to say whether the equations are evaluated for the accepted solution, or for an iterative step. So, I prefer to have a loose tolerance as it very likely catches the problem of a user connecting the valve to a controller that is wrongly configured.
