### ISSUE TITLE
HDirNor in weaBus if HSource is set to connector

### ISSUE THREAD

**Issue by mlauster** [iea-annex60/modelica-annex60#608]
If you set `HSo` to `Annex60.BoundaryConditions.Types.RadiationDataSource.Input_HGloHor_HDifHor` in `ReaderTMY3` and give `HDifHor_in` and `HGloHor_in` via connectors, you get strange results for `HDirNor`.

**Comment by mlauster** [comment]
I made a small example at 

https://github.com/iea-annex60/modelica-annex60/tree/issue608_HDirNor

with inputs

![input](https://cloud.githubusercontent.com/assets/6892690/20869177/1c819206-ba6d-11e6-98e3-6455ca47692d.png)

you get

![output](https://cloud.githubusercontent.com/assets/6892690/20869179/217fab62-ba6d-11e6-9347-8109ff0a7898.png)

The maximum value of input `HGloHor` is 100, the maximum value of output `HDirNor` is 50000000.

@mwetter, can you determine where the reason for this is in `ReaderTMY3`?

**Comment by mwetter** [comment]
@mlauster Thierry will have a look at it.

**Comment by Mathadon** [comment]
```
File 'D:/GIT/modelica-annex60/Annex60/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos' does not exist
```
=) 

This equation is the problem:

```
(HGloHor_in_internal -HDifHor_in_internal)/Annex60.Utilities.Math.Functions.smoothMax(x1=cos(zenAng.zen), x2=epsCos, deltaX=0.1*epsCos)
       = HDirNor_in_internal
```
the output gets magnified by division by a small number at night. This is mathematically correct, but should not be a problem when HDirNor=0, which should be the case at night.

I propose to add a spliceFunction that sets the output to zero when the sun is below the horizon (zenith angle > Pi/2).

**Comment by Mathadon** [comment]
This results into
![screen shot 2016-12-14 at 13 37 36](https://cloud.githubusercontent.com/assets/5970879/21182292/89dd326e-c202-11e6-87f1-83c201422022.png)

so you still get peaks when the sun is very low, but this is correct in my opinion given the current boundary conditions.

**Comment by Mathadon** [comment]
I propose to further limit these peaks by limiting HDirNor to 1000 W/m2 since I'm not entirely sure if the current solution suffices.

**Comment by mlauster** [comment]
@mwetter, @tsnouidui, @Mathadon, thanks a lot, this solution is fine for my applications! I will close this issue, if someone needs further improvements, please reopen it.
