### ISSUE TITLE
Assert sensitive to state variable in JModelica

### ISSUE THREAD

**Issue by agnesramle** [iea-annex60/modelica-annex60#623]
In all these models there is an assert
`if time >= assEqu.t0 and time <= assEqu.t1 or time >= assEqu.t2 and time <= assEqu.t3 or time >= assEqu.t4 and time <= assEqu.t5 then
  assert(noEvent(abs(assEqu.u1 - assEqu.u2) < assEqu.threShold), "Inputs differ by more than threShold" + "\n" + "  time       = " + String(time) + "\n" + "  u1         = " + String(assEqu.u1) + "\n" + "  u2         = " + String(assEqu.u2) + "\n" + "  abs(u1-u2) = " + String(abs(assEqu.u1 - assEqu.u2)) + "\n" + "  threShold  = " + String(assEqu.threShold));
 end if;`
which makes JModelica fail:
Annex60.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase2
Annex60.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase4
Annex60.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase6
Annex60.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase7
Annex60.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase11

The problem is similar to the problem discussed in #564.
Could the assert be removed and the assert be checked in the result verification instead?

**Comment by mlauster** [comment]
I will try to implement something similar to what @mwetter did for #564

**Comment by mlauster** [comment]
Sad that we need to remove this automated test and assertion for the simulation results against the validation threshold, I liked it. @mwetter, I added the difference between simulation results and validation reference results to the regression test scripts, could you please run the regression tests and update the reference results? This is then ready to merge.

**Comment by mwetter** [comment]
@mlauster : If you don't want to remove your test, could you simply use what I implemented on `issue623_ROMAssertions_refactored2`, see commit 1c6a992?
If you prefer this implementation, then please add `assEqu.diff`, `assEqu.threShold` and `assEqu.satisfied` to the plotting variables so they become part of the unit test.

**Comment by mlauster** [comment]
thanks, @mwetter, that looks like a nice solution! I prefer that one. :) Three questions: 
- Why to add `assEqu.threShold` to the unit tests? This shouldn't change and if so, should be visible in `assEqu.diff`. 
- Why do you have a hyteresis in your test condition? Wouldn't it be sufficient to test `satisfied = not (diff > threShold)` ? See commit 883444e10ba1e6576d0dad5a3f3490b81a20613a
- I think it detects only positive deviations from the threshold. Should it be `diff = abs(u1 - u2)`? See commit 883444e10ba1e6576d0dad5a3f3490b81a20613a

**Comment by mwetter** [comment]
@mlauster 

* I proposed to add `assEqu.threShold` as the cost in terms of storage is small (because it is a parameter) and because it is convenient if the results change to see quickly what the threshold is.
* You will need a hysteresis as otherwise, if they solution is around `diff=threShold`, then numerical noise of the integrator could trigger many events that can substantially reduce computing time.
* My mistake, `diff` should be `diff = abs(u1 - u2);`, thanks for catching it.

**Comment by mlauster** [comment]
@mwetter, thanks for your explanations! I implemented `abs` for the difference and included `assEqu.diff`, `assEqu.threShold` and `assEqu.satisfied` to the test scripts in your branch `issue632_ROMAssertions_refactored2`. Unfortunately, Test Case 6 now crashes with the following error message:

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/21357548/d55ee4ee-c6d5-11e6-8187-36f441fd35fc.png)

All other test cases are fine. Do you have an idea how to solve that?

**Comment by mwetter** [comment]
@mlauster : The test for `satisfied` was wrong. I corrected it on the branch `issue632_ROMAssertions_refactored2`, commit 0dbe1f9 
To debug these problems, enable in Dymola the report of event iterations. Then, you can see that `satisfied` oscillated.
Can you please check the other test case now.

**Comment by mlauster** [comment]
@mwetter, thanks for that! All test cases work fine now. If you update the reference results, we are ready to merge!
