### ISSUE TITLE
[JModelica] Change phase in Controls.Continuous.Examples.NumberOfRequests

### ISSUE THREAD

**Issue by agnesramle** [iea-annex60/modelica-annex60#646]
Since sine.y becomes 0 at time=0.25 and pulse.y becomes 1 at time=0.25, i.e. simultaneously, and switching the event generating expression 
numReq.u[1] > numReq.threShold
has some epsilons involved (to avoid chattering it is required that the difference is above a certain threshol to switch), JModelica and Dymola get different results on numReq.y at this time point.

Would it be possible to change the phase of sine to avoid the simultaneous events?

**Comment by tsnouidui** [comment]
This has been fixed.

**Comment by mwetter** [comment]
@tsnouidui Please make a pull request for the master branch so it will be integrated with the library.

**Comment by tsnouidui** [comment]
@mwetter I ran the unit tests on my Ubuntu 16.04 machine but got differences in models which shouldn't have been affected by my changes. Were the reference results updated for Ubuntu 16.04? If not, then wonder whether you could run the tests on Ubuntu 16.04 and update the results?

**Comment by mwetter** [comment]
@tsnouidui : Can you please check my changes. I think it is more useful to output the difference rather than its absolute value.

- [ ] Also, you need to add a validation test in a new package `Diagnostics.Validation` so that it becomes part of the regression tests.

**Comment by mwetter** [comment]
This is now on the `master`
