### ISSUE TITLE
Add check equality block  for JModelica verification tests

### ISSUE THREAD

**Issue by tsnouidui** [iea-annex60/modelica-annex60#647]
This issue is to add a check equality block for JModelica verification. There are a couple of models that have trajectory comparison of an error between an analytic solution and an approximate. These error trajectories have values around 0 and are really dependent on the solver used and the execution order of the model equations.

**Comment by tsnouidui** [comment]
@mwetter @Mathadon  are the master and the issue643_cleanup branch broken? Running --validate-html-only fails?

**Comment by mwetter** [comment]
@tsnouidui Thanks, I corrected the html error on the `master` and the `issue643_cleanup` branch.
