### ISSUE TITLE
black sky temperature computation inconsistency

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#648]
When computing the black sky temperature in `Annex60.BoundaryConditions.SkyTemperature.Examples.BlackBody` using both of the provided options I get:

![screen shot 2017-01-13 at 08 39 10](https://cloud.githubusercontent.com/assets/5970879/21921959/0175b546-d96c-11e6-9b05-de7a96adc37b.png)

There is a delay of 1800s between the two computations, which suggests that one of the input signals for these computations is read using a `CombiTable1Ds` with a wrong delay: `HHorIR` may not need to be delayed by 1800s, or the cloud coverage should be delayed.
@mwetter do you know which one it is, or should I dig further in the definition of TMY3?

**Comment by mwetter** [comment]
@Mathadon Can you please check which of the time series has a wrong offset. Please see also the note about shifting the solar radiation data in the info section of `ReaderTMY3`.

**Comment by Mathadon** [comment]
You mean that I should make sure that both variables are in the reference results somewhere?

**Comment by Mathadon** [comment]
The TMY3 report (http://www.nrel.gov/docs/fy08osti/43156.pdf) contains:

![screen shot 2017-02-17 at 16 22 07](https://cloud.githubusercontent.com/assets/5970879/23087986/5314773e-f52d-11e6-8fd0-8f2c6081a181.png)

but does not seem to reference infrared radiation. So I'm not sure where that data comes from and what convention they use. However all other irradiance are in units of average Wh per hour, so if this would be correct then the current implementation is correct. 

Since we get our files from energyplus: they mention the horizontal infrared radiation in the documentation (https://www.energyplus.net/sites/default/files/docs/site_v8.3.0/EngineeringReference/05-Climate/index.html) but they do not mention the convention that is used. 

I assume that, since EP seems to have added this variable to their weather files, we have to offset the time-axis for this variable to match the TMY3 implementation. I will adjust the implementation accordingly.

**Comment by Mathadon** [comment]
This will be fixed in #670 
New result is:
![screen shot 2017-02-18 at 10 57 35](https://cloud.githubusercontent.com/assets/5970879/23096012/3c280332-f5c9-11e6-90a4-bbf2c61448a9.png)
