### ISSUE TITLE
[JModelica] Switch switches in JModelica but not in Dymola

### ISSUE THREAD

**Issue by agnesramle** [iea-annex60/modelica-annex60#650]
For the model Annex60.Fluid.Chillers.Validation.Carnot_TEva_HighTemperature JModelica switches when chi.con.m_flow becomes equal to 0 while Dymola doesn't in (the switch is a result of actualStream)
chi.sta_a1.T := 273.15 + noEvent(if chi.con.m_flow > 0.0 then chi.con.preDro.port_b.h_outflow else 83680.0) / 4184.0

This results in a difference in the verification results. We have two suggestions on how to force chi.con.m_flow to be slightly bigger than 0.
1. Set a min value of 1e-15 to QCon_flow.u1 (=> chi.con.m_flow will be of size +1e-15 instead of 0)
2. Add a disturbance term for QCon_flow, e.g.
Modelica.Blocks.Math.Add3 QCon_flow(k2=-1, u3=1e-10) "Condenser heat flow rate"

Would any of these suggestions work?

The same problem appears in Annex60.Fluid.HeatPumps.Validation.Carnot_TCon_LowTemperature.

**Comment by tsnouidui** [comment]
This has been addresssed in #656.
