### ISSUE TITLE
Parameter in function splitFacVal

### ISSUE THREAD

**Issue by thorade** [iea-annex60/modelica-annex60#652]
The function `Annex60.ThermalZones.ReducedOrder.RC.BaseClasses.splitFacVal` has some inputs and one output and then it has one `parameter ATot` which I think should not be a parameter, but instead a protected variable. @mlauster did you write that function? Can functions have parameters or do they have to be strictly one of input, output, protected variable?

**Comment by mlauster** [comment]
Hmm, never thought about that. I so far got no warnings, so I assume it's legal code. :) But you are right, I'm not sure about code quality and what would be the best option. Any advantages/disadvantages for both options? Did you get warnings in other environments than Dymola? Any opinions/comments from the other Modelicans?

**Comment by thorade** [comment]
OpenModelica gives a warning, that is how I found it. We could ask the authors of the Spec whether it is legal, or ask on stackoverflow (I would upvote such a question ;-)). And then either tell Dymola or OpenModelica to improve their code checking tool.

**Comment by thorade** [comment]
Also see: https://trac.modelica.org/Modelica/ticket/1594
