### ISSUE TITLE
Refactor models with zero mass flow rate for JModelica 

### ISSUE THREAD

**Issue by tsnouidui** [iea-annex60/modelica-annex60#655]
This issue is to modify models which have zero flow between two volumes with a flow model in-between and different temperatures or compositions in both volumes. These models can lead to arbitrarily large jumps in those temperatures/compositions for arbitrarily small, but sign-changing fluctuations in the mass flow around 0.0.

**Comment by mwetter** [comment]
@tsnouidui Can you please close this or add what other steps are needed before closing it.
