### ISSUE TITLE
change validation test due to tool-dependent choice when using inStream operator

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#657]
There is a difference between JModelica and Dymola in the choice of eps for the inStream operator (see Modelica specification 3.3 p. 179) which affects the calculation for near zero or zero flows. In JModelica the smallest of the flow nominals is used as epsilon for all flows in the implementation whereas Dymola has specific epsilons for each of the flows.
 
This difference affects the verification of Annex60.Fluid.FixedResistances.Validation.FlowJunctionSteadyStateNoPressureDrop where the nominals for spl.res1.m_flow, spl.res2.m_flow, spl.res3.m_flow are not equal. To solve this issue, either:

1. Remove the signals senTem1.T, senTem2.T and senTem3.T from the verification
2. Adjust the nominal values so that spl.res1.m_flow, spl.res2.m_flow and spl.res3.m_flow have the same nominals

**Comment by Mathadon** [comment]
How large is the difference in results due to this? It doesn't make sense to me to change models to get (more or less) exactly the same results in other tools, assuming the result difference is smaller than 1e-6 orso? I'll accept this pull request since the work has been done already :)
