### ISSUE TITLE
Dead link in UsersGuide

### ISSUE THREAD

**Issue by tbeu** [iea-annex60/modelica-annex60#663]
Annex60.UsersGuide.ReleaseNotes.Version_1_0_0 points to a dead link https://github.com/ibpsa/modelica.

**Comment by mwetter** [comment]
@tbeu The ibpsa/modelica repository should be live in the next couple of weeks.

**Comment by tbeu** [comment]
Thanks for leeting me know. I could not have figured it out on my own.
