### ISSUE TITLE
32 bit integer overflow in CalendarTime

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#668]
@tatigabd reports in https://github.com/open-ideas/IDEAS/issues/669#issuecomment-279360410 that OpenModelica (32 bit version) generates warnings when trying to use IDEAS. 
```
[33] 11:01:03 Syntax Warning
[C:/OpenModelica1.9.7/lib/omlibrary/IDEAS-master/IDEAS/Buildings/Validation/BESTEST.mo: 15:25-15:35]: Modelica only supports 32-bit signed integers! Transforming: 3600000000 into a real

[34] 11:01:03 Syntax Warning
[C:/OpenModelica1.9.7/lib/omlibrary/IDEAS-master/IDEAS/Utilities/Time/CalendarTime.mo: 43:5-43:15]: OpenModelica only supports 31-bit signed integers! Truncating integer: 1262304000 to 1073741823
```

This is probably caused by unix time stamps overflowing 31 bit signed integer because `2^30 =  1073741824 > 1.5e9`. We could avoid this by using a `Real` instead, or advice users to use the 64 bit version, which does work.

**Comment by thorade** [comment]
It probably is the same warning with omc 1.11?
Note for myself: to quickly check the omc bitness on Linux, run 
`which omc | xargs file`

**Comment by mwetter** [comment]
We should change the code so it works on 32 bit as some users may not have the option to generate 64 bit.

**Comment by Mathadon** [comment]
We are already using Reals for representing epochs:

```
  constant Real timeStampsNewYear[12] = {
    1262304000, 1293840000, 1325376000,
    1356998400, 1388534400, 1420070400,
    1451606400, 1483228800, 1514764800,
    1546300800, 1577836800, 1609459200}
    "Epoch time stamps for new years day 2010 to 2021";
```

Possibly expressions such as `rem(unixTimeStamp,3600*24)` get translated internally to an expression that requires integers.

Also I can't reproduce the problem since I'm not sure how to launch the 32 bit version of OM? Do you need to install it separately?

We could check with OM if they can identify what equation causes the error?

**Comment by thorade** [comment]
Looks like it is not easily possible to have 32 and 64 bit OMC in parallel on Linux:
https://openmodelica.org/forum/default-topic/2115-32bit-and-64bit-in-parallel

So I installed OpeneModelica 1.11 32bit on my Windows 10 and it was sufficient to just open the Annex60 library to reproduce the warning.
Modelica.SIunit.Time is already a Real, but OpenModelica somehow thinks it is an Integer, this might be a bug in OpenModelica!?
Using the same numbers with .0 attached, tricks OpenModelica into treating it as real Reals and I am able to open the Annex60 library without warning and simulate the Utilities.Time.Examples and Validation.

**Comment by thorade** [comment]
I also opened a ticket in the OpenModelica tracker:
https://trac.openmodelica.org/OpenModelica/ticket/4278
