### ISSUE TITLE
add script for benchmark statistics

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#93]
Add a script that runs a benchmark and extracts the following statistics:

Selected algorithm and tolerance. (Typically Radau with 1E-6.)

* Computation time
* Continuous time states: 6 scalars
* Time-varying variables: 75 scalars
* Sizes of linear systems of equations: { }
* Sizes after manipulation of the linear systems: { }
* Sizes of nonlinear systems of equations: {5, 15}
* Sizes after manipulation of the nonlinear systems: {1, 2}
* Number of numerical Jacobians: 0

* Integration terminated successfully at T = 1200
* CPU-time for integration      : 0.0126 seconds
* Number of (successful) steps  : 126
*   Number of Jacobian-evaluations: 62
*  Number of (model) time events : 1
*   Number of (U) time events     : 0
*   Number of state    events     : 2
*   Number of step     events     : 0

**Comment by damienpicard** [comment]
Is this already done? @mwetter mention in #241 the branch `issue239_statistics`. However, I did not find this branch.

**Comment by mwetter** [comment]
This is now on the master.
