### ISSUE TITLE
add ROM for building according to VDI 6007

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#94]
To use a thermal zone in examples, add a simple RC network model for an office building. This can then by used by ``Annex60.Fluid`` in the examples.

**Comment by mlauster** [comment]
Christoph Nytsch-Geusen proposed another LOM in
https://github.com/nytschgeusen/modelica-annex60/tree/exp_lowOrderBuildingModel/Annex60/Experimental/Benchmarks/CentralHeatingSystem/BaseClasses. 
I will name it 4thOrder in the next sections.

The model already integrated in
https://github.com/iea-annex60/modelica-annex60/tree/issue94_thermalZone
is named 3rdOrder.

Major differences I discovered:
- 3rdOrder:
  - Seperate resistance for windows
  - Consideration of radiative heat exchange within the room (not linearized)
  - Own connector for solar radiation
  - Brings some sub-models
  - Extends BaseClasses to allow modifications
  - Brings its own parameterization tool in Python
  - Is validated with VDI 6007 and ASHRAE 140
- 4thOrder:
  - Solar Radiation affect only outer walls
  - No consideration of indoor radiative heat exchange
  - Extra RC-element for ground
  - exclusively build of MSL and Annex 60 BaseLib elements

I propose to:
- [ ] integrate Christophs Model into this branch
- [ ] name them V1 and V2
- [ ] create a V3 that:
  - [ ] is organized in BaseClasses to allow variations, especially regarding number of RC-elements
  - [ ] uses linearized radiation approach
  - [ ] merges both models to use advantages of both of them
  - [ ] is based on MSL and Annex 60 BaseLib solely if possible

**Comment by damienpicard** [comment]
@marcusfuchs @mlauster Sorry, I forgot to write the feedback of Glenn:

. Can you define asymmetrical resistances and capacities for the walls? This is important as you do not excite the whole wall capacity by small temperature variations
. Multiple outside wall is pratical, as a roof and a wall have very different U-values and capacities.
. Integrating a floor heating would require more capacities and resistances.
. Not clear to me how the SolarRadWeightedSum is working.

**Comment by mlauster** [comment]
I implemented a first version of the overall new models. We have now three different models on different levels that extend each other. This might fulfill the needs of the different institutes.

The branch with the models is under: 
https://github.com/iea-annex60/modelica-annex60/tree/issue94_thermalZoneHarmonized

I think this is a good point to enhance collaboration.
@nytschgeusen, can you please review the models and add your knowledge to them?

Next steps will be:
[ ] Add moisture (MixingVolumeMoistAir)
[ ] Add window model according to VDI 6007-2
[ ] Add equivalent air temperature model according to VDI 6007-1
[ ] Check names
[ ] Add examples
[ ] Add documentation
[ ] Add validation cases

Something I would like to discuss: For cases with outer wall area, window area or inner wall area = 0, the model will crash. Do we need to deal with this cases? If yes, what is the best way? The only way I see is to make all corresponding sub-models and connections conditionally, but this makes the code hard to read.

**Comment by damienpicard** [comment]
@mlauster you could reduce the code for dimensions and splitfactor using the following code:
```
model test
  parameter Real AExt = 1;
  parameter Real AWin = 2;
  parameter Real[2] AArray = {AExt, AWin};
  parameter Real ATot = sum(AArray);

  parameter Integer dimension = sum({ if A>0 then 1 else 0 for A in AArray});
  parameter Real splitFactor[dimension](fixed = false);  //{ if A>0 then {A} else {} for A in AArray};

  parameter Integer j(fixed = false);
initial algorithm 
  j :=1;
  for A in AArray loop
    if A > 0 then
      splitFactor[j] :=A/ATot;
      j :=j + 1;
    end if;
  end for;

end test;
```

**Comment by mlauster** [comment]
After the Leuven meeting, this is the task list for the ongoing work:

- [ ] Avoid default values for conditional statements using the Building's workaround
- [ ] Implement code snippet by damienpicard to shorten code
- [ ] Set min/max values where applicable
- [ ] Link parameterization tool TEASER to models
- [ ] Set up test suite to check all possible model variations
- [ ] Use rad unit instead of real
- [ ] Comment all variables and check types
- [ ] Avoid divisions in equation section (and for parameters possibly), check dsmodel.c
- [ ] Use weatherBus instead of real input
- [ ] Add examples
- [ ] Add documentation
- [ ] Add validation cases

**Comment by mlauster** [comment]
There is one last design decision open for the reduced order models: Indoor radiation exchange can be modeled with a delta or star network.
https://en.wikipedia.org/wiki/Star-mesh_transform
https://en.wikipedia.org/wiki/Y-%CE%94_transform
Star network is faster for high number of walls but includes a deviation for models with more than three walls.
Delta network is always exact but is slower for high number of walls.
For the four element model (the model with the highest number of walls in our lib), the star network is 10% faster and leads to a max deviation of 0.8K.
As the aim is to stick to low number of walls in the ROM package, I vote for delta network and avoid additional deviation.
Are there any other opinions, in particular @mwetter and @nytschgeusen ?

**Comment by Mathadon** [comment]
Hey Moritz,

can you try setting ```Evaluate=true``` in Dymola for the delta network and see how this affects computational speed? Also have a look at the sizes of the linear algebraic loops when you do this :)

**Comment by mlauster** [comment]
If I use `Evaluate:=true`, then both models are nearly at the same speed, thanks, @Mathadon. So I still vote for delta network :)

**Comment by mwetter** [comment]
I vote for the delta network in view of the same speed but higher accuracy.

**Comment by Mathadon** [comment]
Delta is the better option I guess :)

**Comment by mlauster** [comment]
@Mathadon, I set `Evaluate:=true` as command in the command line. Did you actually mean to set it as annotation for some parameter or model instances? Is this in some way similar? I would like to permanently implement `Evaluate:=true` in my model as the user won't intuitively set it this way. Do you know a way how to do it? If both ways are similar, for which parameter or model instances do I need to set it?

**Comment by damienpicard** [comment]
@mlauster for all the parameters that you want to evaluate, use annotation(Evaluate=true); (See Dymola documentation V1, p284 (Evaluate group).

**Comment by Mathadon** [comment]
You have to set `Evaluate=true` in the annotation of all parameters that are used in the linear algebraic loop that is formed by the star point in the RC model, if you want to get the same computation speed.
There is no way to force Evaluate=true in the command line for a model. The user needs to set this :)

**Comment by mlauster** [comment]
Thanks, @damienpicard and @Mathadon! That helped. Anyway, the algebraic loop is connected to upper level models, so the user needs to enable it himself if he would like to achieve top speed.
@Mathadon, how and where do you get this nice overview over the system of equations as in your Modelica paper?

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/13313853/6e85b6a0-dba1-11e5-9a85-a65bdf269830.png)

**Comment by Mathadon** [comment]
It’s in the translation log, under ‘Statistics’

**Comment by mlauster** [comment]
Ok, from my side the Reduced Order Models and all auxilliary models are ready to review! I added documenation, unit tests, examples and validation cases and did all points we discussed in Leuven. @mwetter , could you please review the package, keep an eye on naming and decide where to put the package? I would propose to put `ThermalZones` as new "top-level" package in Annex60.
The current code is in `Experimental` package in branch issue94_thermalZoneHarmonized.

**Comment by nytschgeusen** [comment]
Dear Moritz,

great news, that your reduced order building model is now ready to use !

As discussed we want to use your building model within our simulation scenario for optimal design & optimal control of Activity 2.1. For this purpose I will remove in the next step our old building model and substitute it by yours.

One question: Shall I take the present building model of branch issue94_thermalZoneHarmonized or do you think it will be better to wait until Michael Wetter will have finalized the review process of your models?

All the best

Christoph

-- 
--------------------------------------------------------------
Univ.-Prof. Dr.-Ing. Christoph Nytsch-Geusen

Universität der Künste Berlin
Institut für Architektur und Städtebau 
Fachgebiet Versorgungsplanung und Versorgungstechnik (VPT)
  
Einsteinufer 43-53, 10587 Berlin/Hardenbergstraße 33, 10587 Berlin 
phone: +49 (0) 30 3185-1466/-2097 
fax: +49 (0) 30 3185-19722/-2918  

mail: nytsch@udk-berlin.de 
web: http://www.arch.udk-berlin.de/vpt

**Comment by mwetter** [comment]
@nytschgeusen 
I sent @mlauster a list with changes on Wednesday. However, I think it would be useful if others start using it on an experimental basis and through that contribute to the review before we put it on the `master`.

**Comment by mlauster** [comment]
@mwetter, thanks for your comments, I will do my best to correct everything until easter. Most of the comments are related to documentation and graphical representation.
@nytschgeusen, I would be very happy if you use the model in a 2.1 Use Case! This can prove applicability of the models and reveal potential for improvement. I agree that you can already start using the current models in the branch. However, I need to adapt the existing top-level models within `AixLib` to the newly developed core models. For that it would help to have the models in the `master` and merge them into `AixLib`. So to not loose time in the review process, if you have any comments, please let me know, I will solve existing issues from @mwetter in the meantime and if you have no comments in the next weeks, we could proceed.

**Comment by mwetter** [comment]
@mlauster 
I don't see why it would be easier to have the models in the `master` for merging with `AixLib`. This would make it harder for other libraries who do not yet want the unfinished code and would need to delete them again. I often merge models from development branches to test them in our library before merging them to Annex 60 `master`, using for example
```
git checkout master
git checkout -b syncAixLib  [now this is at the master]
git merge issue94_thermalZoneHarmonized [now you have this branch merged into syncAixLib]
git merge xxxx [any other branch you want to merge for testing in AixLib]
cd path_to_AixLib
python ../mergeAnnex60.py
```
Then, you can merge `syncAixLib` into `AixLib`.

**Comment by mlauster** [comment]
@mwetter, I agree that we should push no unfinished code into the `master`.
My concern about the merging is, what if someone merges the current (or an updated) `master` of `Annex60` into `AixLib master` while I'm still working on `syncAixLib`. Wouldn't that lead to merge conflicts if I merge this updated `AixLib master` into my `syncAixLib` or vice versa?

**Comment by mwetter** [comment]
Yes, that may cause overwrites to `AixLib:master`. If you have multiple developers that sync, you could store `syncAixLib` on the `Annex60` repository and then ask users to merge from `Annex60:syncAixLib` if it exists, and else use `Annex60:master` (and of course all work on the pull requests so that they usually are the same).

**Comment by mlauster** [comment]
I got the following comments by @mwetter to handle:
- [x] Add comments to the parameters or variables, for example in CorGDoublePane
- [x] Also, some should have Modelica.SIunits
- [x] Use a space instead or an asterisk in the html
- [x] Align connectors with grid
- [x] Examples and Validation models should extend from Modelica.Icons.Example . They also need to have revision notes.
- [x] Please add comments to instances
- [x] Examples and validations need to have an entry that runs the regression test
- [x] Please remove all html font formatting
- [x] Please keep the lines short so they can be read in text editors that do not automatically break lines
- [x] Use full names for packages
- [x] It would be nice to use consistent indentation
- [x] Remove Dymola specific stuff

I took care of these points, there is one thing open to discuss:
- Rename `ReducedOrder` to name of guideline (`VDI6007`).

I agree that this would be more specific. But some models extend the guideline's definitions (e.g. `ThermalZoneFourElements`, the guideline defines only two wall elements). And in addition we have some high-level packages (e.g. `Multizone`) in `AixLib` that we would integrate into this package. So it might be misleading to name the package according to the guideline as you cannot find all model theory in this guideline. But I'm open for discussion. :)

**Comment by mwetter** [comment]
@mlauster As the code extends VDI6007 and hence is not identical, I agree that ReducedOrder is a better name.

**Comment by nytschgeusen** [comment]
@mlauster I just finished a first version of our Activity 2.1 system model (solar heating system), in which a solar thermal system with a seasonal hot water storage supplies your building model with thermal energy (compare screenshot):

![systemmodel](https://cloud.githubusercontent.com/assets/6739820/14476854/94298b3c-010a-11e6-9d77-8888e621a684.png)

The parameters configuration is still stupid, but the entire model runs stable and relative fast (a yearly simulation needs less than 40 seconds).

![systemmodel_results](https://cloud.githubusercontent.com/assets/6739820/14476876/b711dda2-010a-11e6-8a26-3aafa894731a.png)

**Comment by mlauster** [comment]
@nytschgeusen, great to hear and see! if you have questions regarding parameters for the ROM related part (and the solar calculations), please let me know. We currently working on a tool to calculate R's, C's and so on from typical building information (called TEASER, we had this topic once in a meeting). It's in Python, but not yet able to export parameter for Annex ROM's.

**Comment by nytschgeusen** [comment]
@mlauster: can I use the teaser tool for the parameterisation of your low-order building model? It would be relatively hard to calculate the absolute thermal capacity of the low-order building model for I given a building construction without any helper tool...

**Comment by mwetter** [comment]
@mlauster : I wanted to start revising the package `Annex60.Experimental.ThermalZones`. I am using branch `issue94_thermalZoneHarmonized`. Running the regression tests causes 17 warnings and 34 errors, including models that don't simulate, such as
`simulateModel("Annex60.Experimental.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase7", stopTime=5.184e+06, numberOfIntervals=0, outputInterval=3600, method="dassl", resultFile="TestCase7");`

Is this the latest version and if so, do the regression tests run successfully for you?

**Comment by mlauster** [comment]
Hm, that sounds like I did something wrong by integrating my .mos-scripts into the process. I added 16 cases, what quite aligns with the number of warnings and errors. I checked my scripts by running them manually in Dymola, what worked fine in all cases. Unfortunately, I couldn't get the unit tests running on my system so far (I fear the problem sits in front of the PC). I will try it again the next days. I added some `plotSignalOperator` statements in my srcipts, could this be a problem?

**Comment by mwetter** [comment]
@mlauster : The scripts are not the problem. I get with dymola 2016 on Ubuntu the following:
```
simulateModel("Annex60.Experimental.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase7", stopTime=5.184e+06, numberOfIntervals=0, outputInterval=3600, method="dassl", resultFile="TestCase7");
 = false
```

**Comment by mlauster** [comment]
@nytschgeusen, regarding TEASER, I would be happy if you use it! We currently prepare a paper for submission as reference to the tool and plan to go immediately public as soon as it is handed in. This is planned for 9th of May.

**Comment by mlauster** [comment]
@mwetter, hmm, the models and scripts run on my system with Dymola 2016 FD01 on Windows 7.

**Comment by mwetter** [comment]
With Dymola 2016 FD01 on Ubuntu, the model works. We should still see how we can fix it as we use Dymola 2016 for the regression tests. I think @Mathadon has reasons for not changing to 2016 FD01.

I have these errors, related to loading the weather files. I will look into these
```
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Experimental/ThermalZones/ReducedOrder/Examples/SimpleRoomOneElement.mos");'.
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Experimental/ThermalZones/ReducedOrder/Examples/SimpleRoomFourElements.mos");'.
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Experimental/ThermalZones/ReducedOrder/Examples/SimpleRoomThreeElements.mos");'.
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Experimental/ThermalZones/ReducedOrder/Examples/SimpleRoomTwoElements.mos");'.
```

There are also many html errors and 16 models with unspecified initial conditions. Do you get the same, and if so, can you please fix these?

**Comment by mlauster** [comment]
Yes, I will take care of initial conditions and html errors.

**Comment by mwetter** [comment]
@mlauster : Can you please address or check off the following if correct.

- [ ] make sure that the reference results 
```
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Examples_SimpleRoomFourElements.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Examples_SimpleRoomOneElement.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Examples_SimpleRoomThreeElements.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Examples_SimpleRoomTwoElements.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase1.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase10.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase11.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase12.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase2.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase3.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase4.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase5.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase6.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase7.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase8.txt
	new file:   Resources/ReferenceResults/Dymola/Annex60_Experimental_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase9.txt

```
are correct, as they were not yet committed in your version.  Check in particular `TestCase6` as I the reference results changed when switching from Annex60.Media.Air to Modelica.Media.SimpleAir (maybe due to the few data points that are used in the reference results).

- [ ]  Consider renaming the ports `signalInput` and `signalOutput` in `ThermSplitter` as these are not signal flows.

- [ ] Change regression tests for `ReducedOrder.Examples` from dassl to radau, which is 2 to 3 times faster.

I removed `volAir(X_start={0,0}),` from the VDI validation as this is not valid because sum(X) = 1 is needed. As I think you set this to model dry air, I changed the medium to `Modelica.Media.SimpleAir`.

**Comment by mlauster** [comment]
@mwetter, thanks for your extensive review, I will take care of your points hopefully in the next days.
I found a small difference in my modelling and the instructions in the guideline VDI 6007, what I will as well fix in the upcoming days. Afterwards, we might need to update the reference results.

**Comment by nytschgeusen** [comment]
@mlauster Where can I find the present version of TEASER ? Does this version exactly fit to the low-order model, which we develope and discuss within this issue ?

**Comment by mlauster** [comment]
@nytschgeusen, that's the point, the present version is private on github and we will go open source around 9th of May. The current version cannot directly address the Annex60 models. We are currently working on this and the released version will be able to address them.

**Comment by mlauster** [comment]
I added some modifications regarding the handling of solar radiation through windows. Exterior wall areas and window areas with the same orientation as the incoming solar radiation are not considered in the radiation distribution any more. This calculation is done for each orientation seperately. 
This leads to some minor changes in the model's API. 
@nytschgeusen, you need to update your model according to the following:

1. Enter `nOrientations` for ThermalZone
2. Define exterior wall areas, window areas and transparent areas as vectors, one entry per orientation. The order must be the same as the incoming solar radiation at the `solRad` port.
3. Delete the aggWindow element.
4. Connect all solar radiation signals directly to `solRad`.

Sounds more work as it is, see `Examples` for guidance. You could also wait until we merge it in the `master`, there might be some name changes of connectors and parameters in the next weeks.

@mwetter, I will now start integrating your review comments.

**Comment by mlauster** [comment]
Today, we released TEASER at https://github.com/RWTH-EBC/TEASER. @nytschgeusen, you can use this tool to calculate your resistances and capacitances and export a Modelica template for the Annex60 ROMs.

**Comment by mlauster** [comment]
Here is an update of solved issues and still open points:
- [x] fix HTML errors. @mwetter, I fixed all errors I found using linter-hmtlhint in Atom.
- [x] fix initial conditions
- [x] Consider renaming the ports `signalInput` and `signalOutput` in `ThermSplitter` as these are not signal flows
- [x] Change regression tests for `ReducedOrder.Examples` from dassl to radau, which is 2 to 3 times faster
- [x] Implement consideration of solar radiation through windows exactly as given in VDI 6007-1
- [x] Pass all 12 VDI 6007-1 validation cases
- [x] Reformulate documentation where necessary
- [ ] Check reference results for unit tests. @mwetter, due to some modifications, the results changed after you created the reference results. Could you run the unit tests again and commit a new set of reference results? I will then check them.
- [ ] Set parameters to final where applicable
- [ ] Set models as protected where applicable
- [ ] Rename models and parameters where necessary
- [ ] Move `ThermalZones` out of `Experimental` as new high-level package in `Annex60`

**Comment by mlauster** [comment]
@mwetter, I fixed all errors occuring in regression tests you mentioned above (on 27 April) and send me by mail (7 errors were still remaining, 6 html errors and one simulation error).
For the simulation error (validation test case 12 failed to simulate on Dymola 2016), I got the following message in Dymola 2016

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/16043595/adf1d698-3240-11e6-84c4-7b3fc3e856e3.png)

I solved that by adding

`port(T(start=300))` to `preTem`. However, as this doesn't seem to be an issue with Dymola 2016 FD01, I can remove this when we switched to Dymola 2016FD01 for regression tests. So long, I would keep it. @mwetter, can you run the regression tests, update the reference results and report if any other errors occur?

**Comment by mwetter** [comment]
@mlauster The models all run successfully, but many reference results are quite different, see for example:
![figure_1](https://cloud.githubusercontent.com/assets/1329080/16099383/e1f88e9c-330c-11e6-9bb9-73bfd51a3598.png)

As I don't know whether this change is intentional or not, I did not accept the new reference results. Can you please run the regression tests, commit any new results (if you think the change in results is correct). I can run the reference results again on Linux but this should only give very small differences, and then commit to the master.

**Comment by mlauster** [comment]
@mwetter The changes are intended, for `reference.y[1]`, I changed the interpolation to stepwise (as the VDI 6007-1 seems to have it like that). For `TAir` (and all other) I did a lot of work while the Annex60 Meeting in Miami and we now fullfill all validation requirements from VDI 6007-1. I checked that (using the regression test scripts) after the last commit. Can you commit your reference results?

**Comment by mwetter** [comment]
@mlauster 
I committed the reference results and did some minor reformatting of the comments.
I also merged the `master` to this development branch.
From my point of view it is ready to merge to the `master`.

However, as VDI has such stringent accuracy requirements, I wonder how you ensure that they remain satisfied if result change slightly (due to a change in Modelica tool, compiler or base classes). Would it make sense to add an assertion in the validation models that would trigger an error if the accuracy as required by VDI is not satisfied? Such a test could be added after merging them to the master in a separate new branch, but I think it would be useful to have a test that ensure that the models stay compliant with the VDI requirements.

**Comment by mlauster** [comment]
@mwetter, I have a Python script to post-process the simulation results and compare them to the reference results. This script basically executes the regression test .mo-files for the validation cases, opens the results and does the comparison, stating which test cases have been passed successullfy. The main challenge are that the VDI guideline gives mean hourly values, only for day 1, 10 and 60 and that different variables need to be checked (with different ranges to hold), depending on the validation case. So my script calculates the mean values for the simulation results, reduces the comparison to the three mentioned days and checks if the hourly differences between simulation and reference are within the bounds for the specific variable (max diff temperature +/-0.1°C, max diff heat flow +/- 1W). I tried to implement the entire process in Dymola once, but that seemed cumbersome. Do you see a way to integrate such a Python script in the regression tests?

**Comment by mwetter** [comment]
@mlauster 
Using a Python script for that is not good as other tools (such as JModelica and OpenModelica) use their own code for regression testing and hence would not run your Python code. 
I suggest to use `when` statement together with an hourly average. In the BESTEST validation of `Buildings`, we use such an hourly average. If you combine them in a block with a `when` statement, then you can probably do a pretty generic implementation and parametrize it for the different test cases.

**Comment by mlauster** [comment]
@mwetter, sounds like a good idea! But as might take take some time, I vote as well for merging the branch into the `master` and implement this afterwards in a new branch and issue. I will create a merge request.
